### ISSUE TITLE
Warning: Prop `href` did not match on accented usernames

### ISSUE THREAD

**Issue by andrecasal** [epicweb-dev/epic-stack#101]
Probably not a big deal, but usernames can be accented and this causes a href mismatch between the server and the client, because the href is URL encoded client-side:

<img width="803" alt="Screenshot 2023-05-26 at 08 37 40" src="https://github.com/epicweb-dev/epic-stack/assets/22457463/cbfd3d7f-bbce-4461-8449-7598ba840658">

Should be a quick fix. I think the right approach would be to explicitly URL encode the href.

**Comment by andrecasal** [comment]
Actually, there's a larger point here: URLs should be user- and SEO-friendly, i.e. without diacritics (this point is also relevant to search by the way).

I'm not sure what the solution should be, but I can think of a few:
- Don't allow usernames to have diacritics (bad UX for non-english usernames)
- Allow usernames to have diacritics and practice proper URL encoding (bad for SEO and URL sharing)
- Allow usernames to have diacritics, but filter diacritics out of the URLs (we need to filter out diacritics when comparing usernames and assume "Andre" and "André" are the same username, for example, and enforce uniqueness)

**Comment by kentcdodds** [comment]
What does twitter do? I think we should just follow what twitter does. I think that means, no diacritics in the username.

**Comment by kentcdodds** [comment]
I verified that twitter only allows letters (non-diacritics), numbers and underscores. So that's what we'll do.
