### ISSUE TITLE
Zod: async function during sync operation

### ISSUE THREAD

**Issue by andrecasal** [epicweb-dev/epic-stack#102]
The signup page is showing this error:

<img width="1029" alt="Screenshot 2023-05-26 at 11 01 31" src="https://github.com/epicweb-dev/epic-stack/assets/22457463/e99d37e2-a7ba-4602-b2b9-096edf8a4714">

I'm not familiar enough with Conform and Zod to know how to fix this, but I think this pertains to the `isEmailUnique()` function being async, but the client-side validation running sync.

**Comment by edmundhung** [comment]
There is a bug on the [signup schema](https://github.com/epicweb-dev/epic-stack/blob/main/app/routes/_auth%2B/signup.tsx#L24-L30) that set a default implementation for `isEmailUnique`.

It should be optional instead:
```ts
function createSchema(
  constraints: {
    isEmailUnique?: (email: string) => Promise<boolean>
  } = {},
)
```

**Comment by andrecasal** [comment]
I think we also need to add a `return` here:
```tsx
if (typeof constraints.isEmailUnique === 'undefined') {
	ctx.addIssue({
		code: z.ZodIssueCode.custom,
		message: conform.VALIDATION_UNDEFINED,
	})
	return // 👈 add return statement
}
```
