### ISSUE TITLE
simplify tsconfig include

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/epic-stack#141]
https://github.com/epicweb-dev/epic-stack/blame/c196386d1b5fb6c7f273306f1bbd26701b60dbca/tsconfig.json#L1-L7

```json
        "include": [
                "remix.env.d.ts",
                "**/*.ts",
                "**/*.tsx",
                "./tests/setup/setup-test-env.ts"
        ],
```

we have ` "**/*.ts"`.
can we remove `"remix.env.d.ts"` and `"./tests/setup/setup-test-env.ts"` ?

**Comment by kentcdodds** [comment]
I believe so, yes.
