### ISSUE TITLE
Init script incompatible with github user-based URLs

### ISSUE THREAD

**Issue by mattfysh** [epicweb-dev/epic-stack#149]
When using github fine-grained tokens instead of personal access tokens (now designated as "legacy" by github), you need to create a token for each account (personal and org), as these new token types cannot be scoped beyond a single account

Then, when cloning and working locally with git CLI, the CLI will only allow you to use one of these tokens as default. If your personal account is used by default and you want to work with a repo in an org, you need to use the org's name as your git username, e.g.

`git clone https://myorg@github.com/myorg/myrepo`

When I use this style of repo URL with the init script, it seems to be converted by the init script into `git@github.com/myorg/myrepo`, which will fail as git will attempt to connect to the repo using the default token, and not the token created for "myorg" - this will cause the initial setup script to fail at the git push step

**Comment by kentcdodds** [comment]
Hey @mattfysh,

Is there a reason you can't update to non-legacy access tokens? I'm not sure I want to put effort into supporting something designated as legacy unless there's a very good reason.

**Comment by mattfysh** [comment]
Hey Kent, I'm talking about the new fine-grained tokens released in October of last year, apologies if that wasn't clear:

https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/

I mention the legacy PATs because I assume you may still be using them (or not using an org) if you haven't run into this issue yet

**Comment by kentcdodds** [comment]
I'm not sure I understand. You're supposed to provide the GitHub URL to the CLI (like `https://github.com/kentcdodds/solid-waffle` for example). When that URL gets parsed, the command that gets executed is: `git remote add origin git@github.com:kentcdodds/solid-waffle.git` which is what GitHub recommends on their new repo page:

<img width="1191" alt="Screenshot of the GitHub new repo page showing the same command as noted" src="https://github.com/epicweb-dev/epic-stack/assets/1500684/77fca061-1c88-4170-b2b2-77d07c1f5f44">

Did you perhaps provide a different URL to the CLI?

**Comment by kentcdodds** [comment]
I'll note that `githubParts.auth` is `null` when you pass `https://github.com/kentcdodds/solid-waffle` so I don't think that would solve it. I'm guessing you're passing a different URL than what's expected.

**Comment by mattfysh** [comment]
I think perhaps this is not clicking for you because you may have not started using the fine-grained tokens yet?

You can visit this URL to check which type of tokens you are currently working with: https://github.com/settings/tokens?type=beta

The thing to understand about github's new token type is that you can no longer have a single token that works with all your personal and org accounts, you need to create a new token for each account, e.g.

* one token for "kentcdodds" personal account; and
* one token for "epicweb-dev" org account

When using the default git CLI that comes with macOS, your github username and access token are stored in OSX Keychain so that you don't need to type out your credentials each time you run git pull/push/etc.

How does the CLI know which token to use when using the new fine-grained tokens? It looks in Keychain and use the first token it finds - which may not be the one that works, e.g. if you do `git clone github.com/epicweb-dev/epic-stack` but the first token it finds is for the "kentcdodds" personal account, the command will fail on auth.

I've found the easiest way for the CLI to know which token to use from your keychain is to include the account name as the username in the git remote url, e.g. if you do `git clone https://epicweb-dev@github.com/epicweb-dev/epic-stack` the full URL is used as the remote origin URL **and** it also now uses the correct token from your keychain. Note: pay close attention to the username preceding the `@` symbol in the pull command.

I'd also point out that in your screenshot, just above the cropped view you'll see an HTTPS/SSH toggle. It looks like your UI is defaulting to the SSH selection, while Github recommends to use HTTPS: https://docs.github.com/en/get-started/quickstart/set-up-git#connecting-over-https-recommended

**Comment by kentcdodds** [comment]
Thanks for your patience with me @mattfysh!

I'm guessing you're right on this. So it seems like the solution involves more than just knowing the owner and name of the repo but we also need the token name. Maybe it would be better if we have folks copy the code GitHub offers on that screen and run that?
