### ISSUE TITLE
The site.webmanifest needs a mandatory start_url

### ISSUE THREAD

**Issue by andrecasal** [epicweb-dev/epic-stack#171]
As per [MDN docs](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable#required_manifest_members), the site.webmanifest requires a `start_url` so the website becomes installable.

I suggest adding `"start_url": "http://localhost:3000",` so users can test app installation during development.

**Comment by kentcdodds** [comment]
What if we move the `site.webmanifest` to be a resource route so the `start_url` can be dynamic based on the domain? That way people don't have to worry about keeping it up-to-date and it'll work for preview deploys and staging etc.

**Comment by kentcdodds** [comment]
Actually, looking at [this](https://developer.mozilla.org/en-US/docs/Web/Manifest/start_url) it appears a relative URL would suffice. Maybe we can set it to `./`?

**Comment by andrecasal** [comment]
Let me try that out...
