### ISSUE TITLE
Found artifacts from Rocket Rental :)

### ISSUE THREAD

**Issue by andrecasal** [epicweb-dev/epic-stack#176]
Found artifacts from Rocket Rental [here](https://github.com/epicweb-dev/epic-stack/blob/f21bbe93ce26b3ff391874a102e8a7c83319be11/app/routes/users%2B/%24username.tsx#L115C7-L124) and [here](https://github.com/epicweb-dev/epic-stack/blob/f21bbe93ce26b3ff391874a102e8a7c83319be11/prisma/seed.ts#L26-L28), mentioning renters and hosts 😄

**Comment by kentcdodds** [comment]
Fixed, thanks!
