### ISSUE TITLE
Vitest fails on clean installation

### ISSUE THREAD

**Issue by andrecasal** [epicweb-dev/epic-stack#189]
GitHub Action result on a clean installation (without deploying to Fly):

<img width="916" alt="Screenshot 2023-06-15 at 15 06 44" src="https://github.com/epicweb-dev/epic-stack/assets/22457463/135eec46-96fd-4c6e-8ac6-555685126c19">

**Comment by andrecasal** [comment]
I tried again deploying to Fly and Vitest passed, but I can't identify anything the remix.init script might be doing differently that would influence this test.

**Comment by kentcdodds** [comment]
We're set here now
