### ISSUE TITLE
Proposal to Disable ESLint Caching due to Potential Bugs with typescript-eslint

### ISSUE THREAD

**Issue by milamer** [epicweb-dev/epic-stack#203]
Hey there,

Really appreciate all the work you're doing on this package. It's been super useful for me!

So, here's the thing: I've been running into some hiccups with ESLint caching when using typescript-eslint. It's like ESLint caching doesn't quite play nice with typescript-eslint. Some changes, especially minor ones in TypeScript types, interfaces, and such, sometimes slip through the cracks. ESLint doesn't always lint these properly because of its caching.

There's already a discussion about this problem over on the TypeScript-ESLint repo (see [#6373](https://github.com/typescript-eslint/typescript-eslint/issues/6373)). It seems like the best way to get around this issue is to turn off ESLint caching for this package.

Sure, turning off caching might slow things down a bit, but I think it's worth it to avoid any sneaky bugs.

Would love to hear your thoughts on this.

Cheers,
Chris

**Comment by kentcdodds** [comment]
You're right. I've had issues with caching as well. On top of that it doesn't really speed up much other than running the script directly and when I'm doing that I often don't want the cache anyway. It's been removed 👍 Thanks for opening the issue!

**Comment by onemen** [comment]
in my project i am usually add lint:clean script to run Eslint without using the cash

**Comment by kentcdodds** [comment]
I don't personally run the lint script that often anyway. I just use the editor plugin 🤷‍♂️
