### ISSUE TITLE
Link in Native ESM Decision Doc 404s

### ISSUE THREAD

**Issue by aydrian** [epicweb-dev/epic-stack#210]
In the [Native ESM Decision Doc](https://github.com/epicweb-dev/epic-stack/blob/main/docs/decisions/006-native-esm.md), You link to the talk _More than you want to know about ES6 Modules_, however the link https://kentcdodds.com/talks/more-than-you-want-to-know-about-es-6-modules 404s.

**Comment by kentcdodds** [comment]
Hmmm, it seems to work for me. What do you see?

**Comment by aydrian** [comment]
Maybe I was just confused on the layout. The title of the page is "404: Talk Not Found", but I did see it with all the other cards, it was on the right side. I thought I needed to click on the talk title which took me to the top of that same page with the same time. I'm now seeing in that talk card there are links. It's just not what my eyes were drawn to.

**Comment by kentcdodds** [comment]
Oh yeah, I'm getting that also. Maybe it has to do with the recent v2 meta changes. I also noticed some viewport issues on my phone which could be related.

**Comment by onemen** [comment]
i am checking it right now

**Comment by onemen** [comment]
@kentcdodds,

i've the site with the latest commit before `v2 meta` and it work.

do you want to revert the changes until we find the regression?

**Comment by kentcdodds** [comment]
Sure 👍

**Comment by kentcdodds** [comment]
Deploying the revert right now. https://github.com/kentcdodds/kentcdodds.com/commit/9c45453778d74abf5883ac7e93997da5ab185222
