### ISSUE TITLE
esbuild WARNING

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/epic-stack#211]
I see this on Windows 10.
```shell
▲ [WARNING] "tsconfig.json" does not affect esbuild's own target setting [tsconfig.json]

    tsconfig.json:11:4:
      11 │     "target": "ES2022",
         ╵     ~~~~~~~~

  This is because esbuild supports reading from multiple "tsconfig.json" files within a single
  build, and using different language targets for different files in the same build wouldn't be
  correct. If you want to set esbuild's language target, you should use esbuild's own global
  "target" setting such as with "target: 'es2022'".
```

we use `esbuild` - version 0.18.5, only for `server-build/index.js`, the rest of the code is handle by remix with its `esbuild` - version 0.17.6
esbuild [changelog](https://github.com/evanw/esbuild/releases/tag/v0.18.0) - indicate that esbuild no longer use `tsconfig.json` target as its target.

I think it is bet to keep our version of esbuild in-sync with remix version. when remix will update to esbuild version 18+ we can drop the `target` from our `tsconfig.json`

**Comment by kentcdodds** [comment]
Good idea 👍
