### ISSUE TITLE
Deployment setup fails if project name has capital letters

### ISSUE THREAD

**Issue by NotLuksus** [epicweb-dev/epic-stack#218]
When running `npx create-remix@latest --typescript --install --template epicweb-dev/epic-stack`
You get asked `Where would you like to create your app?`, I entered `HousingHub`, from how I know it from other frameworks like Next, you usually get an error there to only use lower case.
Here however you don't and fly doesn't like that.
<img width="822" alt="image" src="https://github.com/epicweb-dev/epic-stack/assets/28923284/0f9f130c-b0e5-4e73-9e7e-5868d8e0b17a">
Adding a .toLowerCase() to the APP_NAME in [remix.init](https://github.com/epicweb-dev/epic-stack/tree/main/remix.init/index.mjs) line 32, probably does the trick here.

**Comment by kentcdodds** [comment]
Nice catch. That solution sounds good to me. Would you like to make a pull request?

**Comment by NotLuksus** [comment]
Yeah sure, will do later tonight!
