### ISSUE TITLE
Update package.json engines.node to ">=18"

### ISSUE THREAD

**Issue by kiliman** [epicweb-dev/epic-stack#227]
With the current version of Node.js being v20, I think it would be a good idea to update _package.json_ node engine version.
```json
"engines": {
  "node": ">=18"
}
```

**Comment by kentcdodds** [comment]
The version in production (as configured in the Dockerfile) is 18, so we should be consistent with that. Maybe we should add documentation on the fact that you need to update both of those values...

**Comment by kiliman** [comment]
Ah, I see. I guess I'll need to use my nodeenv version picker (I use `asdf`).
