### ISSUE TITLE
Update decision docs for email to use Resend instead of Mailgun

### ISSUE THREAD

**Issue by giovannibenussi** [epicweb-dev/epic-stack#241]
The [Email Service Docs](https://github.com/epicweb-dev/epic-stack/blob/main/docs/decisions/002-email-service.md) still says "We selected Mailgun because...", even if the `email.server.ts` is already working with resend.

We need to update the wording here. I'd do it but I wasn't part of the decision-making of this so I'd prefer that someone else does this. This email is just a friendly reminder to do so :-)

**Comment by kentcdodds** [comment]
Hi @giovannibenussi!

You'll notice that the decision document you linked to has a status of "superseded by [017](https://github.com/epicweb-dev/epic-stack/blob/main/docs/decisions/017-resend-email.md)" which explains why we changed from mailgun. I want to keep the decision documents pretty untouched from the time they were initially written to keep an easy-to-browse history of decisions.

Thanks though!
