### ISSUE TITLE
Vscode tailwindcss intellisense not working with epic stack

### ISSUE THREAD

**Issue by Amrender-Singh** [epicweb-dev/epic-stack#250]
The Tailwindcss intellisense is not working for the epic stack repository.  I suspect the problem is the tailwind config file, currently our config file is written in typescript whereas the extension supports config file in  javascript. In case I change the config file to javascript the intellisense starts working.

**Comment by kentcdodds** [comment]
Sounds like a bug in the tailwind extension. Could you open an issue over there?

**Comment by Amrender-Singh** [comment]
Opened the issue in tailwindcss intellisense: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/813
