### ISSUE TITLE
ErrorBoundary missing on root

### ISSUE THREAD

**Issue by vinstah** [epicweb-dev/epic-stack#252]
I've found that there is no `function ErrorBoundary()` on root.tsx. If a route manually typed in to url that didn't exist it shows an ugly error.

**Comment by kentcdodds** [comment]
You're right. We definitely should have this. Would you be willing to add something?

**Comment by vinstah** [comment]
Yeah, I can do that.
I see in the Remix docs they have this [example](http://remix.run/docs/en/main/route/error-boundary-v2) though, Epic stack already uses an error-boundary.tsx component I can reuse that
