### ISSUE TITLE
npm install fails on Node 18.6.0 and Mac M1

### ISSUE THREAD

**Issue by rajeshdavidbabu** [epicweb-dev/epic-stack#266]
I am getting hit with the following errors when I attempt to do an npm install

Node version: 18.6.0
Machine: Macbook Pro M1

<img width="1020" alt="Screenshot 2023-07-05 at 13 00 53" src="https://github.com/epicweb-dev/epic-stack/assets/15684795/c6aff655-bb13-43e0-bb69-8dbb976a4226">

**Comment by rajeshdavidbabu** [comment]
Happy to share more info, looking for a quick fix to see if I am doing anything wrong !

**Comment by kentcdodds** [comment]
It looks like you've got issues with node-gyp and better-sqlit3. I believe they have documentation on this: https://github.com/WiseLibs/better-sqlite3/blob/master/docs/troubleshooting.md#install-the-node-gyp-toolchain

Another idea is to stick the error message into ChatGPT and see what it tells you.

**Comment by kentcdodds** [comment]
Let me know if you don't get things working.
