### ISSUE TITLE
Enforce case-insensitive uniqueness of username and email address

### ISSUE THREAD

**Issue by mediabakery** [epicweb-dev/epic-stack#271]
At the moment it is possible to create two user accounts with the same e-mail address.
e.g. `hello@example.com` and `Hello@Example.com`
The same applies to usernames.

### potential resulting problems:

- User logs in with wrong username because they capitalizes it
- Multiple accounts with the same email address

### Underlying problem:

SQlite does not offer a bulletproof solution to search case-insensitive. see [documentation](https://www.prisma.io/docs/concepts/components/prisma-client/case-sensitivity#sqlite-provider).

### Options:

- Enable limited SQlite support for  [case-insensitive comparisons of ASCII characters](https://www.sqlite.org/faq.html#q18)
   **pro:** 
   - solved at storage level
   
   **cons:**
   - only limited support
   - needs a schema migration
   - It cannot be expressed via the prisma scheme
   
- Convert input to lower case at service level
   **pro:**
   - works also for non-ASCII characters
   - no schema migration needed
   - can be done during the input cleanup (e.g. `trim()`)

   **cons:**
   - it's not enforced by the storage => this must be implemented in several places
   - a data migration / cleanup should be done to prevent any incorrect behavior of the existing accounts.

**Comment by kentcdodds** [comment]
I'm open to implementing both options. Supporting case-insensitive comparisons is a desireable feature for other things as well, so I think it would be helpful to have that set up from the get-go. I'm afraid I don't know what would be involved there though. I'm open to suggestions.

For now, I think converting input to lower-case would be a good idea for username and email.
