### ISSUE TITLE
Confetti Canvas Horizonal Scroll

### ISSUE THREAD

**Issue by bradymwilliams** [epicweb-dev/epic-stack#272]
On fresh install, the Confetti canvas creates a horizontal scrollbar

Could be potentially be fixed position over absolute but I'm not familiar with the purpose of this feature so I hesitate to say for sure

**Comment by kentcdodds** [comment]
Thanks for the issue @bradymwilliams! We definitely don't want to have the canvas be a problem. I'm thinking you're right that we could just make it a fixed position. Would you be interested in working on a fix for that?

**Comment by kentcdodds** [comment]
I think this should be resolved now.
