### ISSUE TITLE
notes scrollbars visible all the time

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/epic-stack#277]
this is how it looks on windows 11 after 62d887af06697051a849de55e9ef8f35075c01dc

![notes_scroll1](https://github.com/epicweb-dev/epic-stack/assets/3650909/fdff674d-81ee-4d99-b675-4ab749008f1f)

**Comment by kentcdodds** [comment]
I was hoping that using `overflow-auto` would make those not show up unless they were necessary. Ugh. How annoying. Scrollbars are the worst.

**Comment by kentcdodds** [comment]
I guess we had some `overflow-scroll` in there. Had to add `overflow-x-hidden` in there as well because the presence of the scrollbar on the y axis makes it necessary I guess. Ugh.

**Comment by onemen** [comment]
you can add `tailwind-scrollbar` to make scroll bars look better with `scrollbar-thin scrollbar-thumb-scrollbar` like you do on `kcdshop`

**Comment by kentcdodds** [comment]
I'm not 100% certain changing the styling of the scrollbar is a great idea. I wouldn't want it to be the default in the Epic Stack. I'm just annoyed that it appears at all. I wish everyone just did what mobile/macOS does and hid the scrollbar. 🤷‍♂️
