### ISSUE TITLE
npm run dev throwing [ERROR] could not resolve

### ISSUE THREAD

**Issue by jamesone** [epicweb-dev/epic-stack#278]
I have followed the getting started guide & have done a npm install. When I run `npm run build` or `npm run dev` I get the following errors:

```
 app/routes/resources+/theme/index.tsx:4:27:
      4 │ import { useFetcher } from '@remix-run/react'
        ╵                            ~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@remix-run/react" here because it's not listed as a dependency of this package:

    ../../.pnp.cjs:38:33:
      38 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "@remix-run/react" as external to exclude it from the bundle, which will remove this error.


✘ [ERROR] Could not resolve "react"

    app/routes/resources+/theme/index.tsx:5:23:
      5 │ import * as React from 'react'
        ╵                        ~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "react" here because it's not listed as a dependency of this package:

    ../../.pnp.cjs:38:33:
      38 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "react" as external to exclude it from the bundle, which will remove this error.


✘ [ERROR] Could not resolve "remix-utils"

    app/routes/resources+/theme/index.tsx:6:29:
      6 │ import { safeRedirect } from 'remix-utils'
        ╵                              ~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "remix-utils" here because it's not listed as a dependency of this package:

    ../../.pnp.cjs:38:33:
      38 │           "packageDependencies": [\
      
.... The errors keep coming for many more packages.
```

My environment is as follows:
- Node: 18
- Npm: 8.6.0
- Computer: m1 mac v 12.3

Any idea? I have tried re-cloning, re-installing node_modules, clearing cache.

**Comment by kentcdodds** [comment]
It looks like you're using yarn? Epic Stack only supports npm. I'm afraid we don't spend any effort to make it work for other package managers.

**Comment by jamesone** [comment]
@kentcdodds Yeah it's strange because I am running the `build/dev` commands using `npm`. But it's still throwing errors relating to `yarn pnp`. I will have another debug tonight. Perhaps this is an environment issue

**Comment by jamesone** [comment]
So I found the issue and it was a weird one for sure! I had a `.pnp.cjs` file in my home working directory (`~/.pnp.cjs`). 

To fix the issue I simply removed this `rm ~/.pnp.cjs` and I was able to run the commands just fine!

As for the WHY - I didn't have time to figure out why `npm run <cmd>` was being affected by this file.

**Comment by kentcdodds** [comment]
That is odd! I'm glad you worked it out!
