### ISSUE TITLE
Upgrade to Native ESM

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/epic-stack#28]
I'm pretty sure we want to use native ESM in this project. I believe Remix v2 will default to native ESM. It may be more trouble than it's worth, but I think it's worth looking into.

**Comment by onemen** [comment]
how about we finish updating to Remix v1.16 + ESM on [rocket-rental](https://github.com/epicweb-dev/rocket-rental/pull/12) then we can use same approach to update this project to ESM
