### ISSUE TITLE
Script to generate all fallback fonts at once

### ISSUE THREAD

**Issue by matt-kinton** [epicweb-dev/epic-stack#293]
(this might be a better feature request in the fontpie repo itself)

It's pretty tedious and slightly error prone generating 10+ font fallbacks and copying them individually into the `fonts.css` file. It would be handy if we could provide a script to generate all the font fallbacks required for the app.

ChatGPT and I put together a basic script that does this although it probably needs some more thinking through / refinement, it definitely saved me a lot of time though! 

### Usage

`npx node ./other/generate-fallback-fonts.cjs ./public/fonts/inter/inter.css `

### Script

```javascript
const fs = require('fs');
const parse = require('css-parse');
const fontpie = require('fontpie-calc');
const path = require('path');

function parseFontFace(cssText) {
  const ast = parse(cssText);
  const fontFaces = ast.stylesheet.rules.filter((rule) => rule.type === 'font-face');

  const fontFaceObjects = fontFaces.map((fontFace) => {
    const fontFamily = fontFace.declarations.find((decl) => decl.property === 'font-family').value;
    const fontStyle = fontFace.declarations.find((decl) => decl.property === 'font-style').value;
    const fontWeight = fontFace.declarations.find((decl) => decl.property === 'font-weight').value;

    const srcDeclaration = fontFace.declarations.find((decl) => decl.property === 'src');
    const srcValue = srcDeclaration.value.replace(/url\(['"](.+?)['"]\).*/, '$1').split('?')[0];

    return {
      family: fontFamily,
      style: fontStyle,
      weight: fontWeight,
      src: srcValue,
    };
  });

  return fontFaceObjects;
}

// load file from args
const [, , file] = process.argv;
if (!file) throw new Error('No file specified');

// read file
const css = fs.readFileSync(file, 'utf8');

const fontFaces = parseFontFace(css);

const fonts = fontFaces.map((fontFace) => {
  const { family, style, weight, src } = fontFace;

  // load fontFile relative to css file
  const cssFileFolder = path.dirname(file);
  const fontFile = path.join(cssFileFolder, src);

  return fontpie(fontFile, { name: family, style, weight });
});

const fontPieCss = fonts
  .map(
    ({
      fontFamily,
      fontStyle,
      fontWeight,
      fallbackFont,
      ascentOverride,
      descentOverride,
      lineGapOverride,
      sizeAdjust,
    }) =>
      `
@font-face {
  font-family: "${fontFamily} Fallback";
  font-style: ${fontStyle};
  font-weight: ${fontWeight};
  src: local('${fallbackFont}');
  ascent-override: ${ascentOverride};
  descent-override: ${descentOverride};
  line-gap-override: ${lineGapOverride};
  size-adjust: ${sizeAdjust};
}`.trim()
  )
  .join('\n');

console.log(fontPieCss.trim());
```

**Comment by kentcdodds** [comment]
Hi @Mattinton!

When I choose a font, it normally comes with a css file with all this stuff implemented already and I just copy/paste that thing.

Considering choosing a font is something you really only do once in a project, I don't think it makes sense to include a script in the project. However, I think adding this to the docs makes sense if you're interested in adding a page for fonts!

**Comment by Mattinton** [comment]
Hey!

I don't think I explained brilliantly above, this is for generating the fallback font's from `fontpie` all in one go! For example for `Inter` you've got to manually type out the fontpie command (`npx fontpie ...`) 15ish times to generate the correct fallbacks.

That said, I think you're right it's a basically a one-off process so probably doesn't require bloating the repo with a script, but might help some people if documented 😄

**Comment by xHomu** [comment]
This is super cool! Nice job, Mattinton. 

Maybe it makes more sense to publish as a npx command to add font fallback to any font.css?

**Comment by Mattinton** [comment]
Hey guys, sorry I've been on holiday and then ill since raising this issue, @kentcdodds I'll work update the docs over the weekend 😄

**Comment by xHomu** [comment]
@Mattinton this is actually super valueable work, here's how much timings improved when I ripped out Adobe Typekit from a project and implemented all the font best practices:

![image](https://github.com/epicweb-dev/epic-stack/assets/84349818/3fc709ba-7d4f-436e-b452-85cad7247903)

**Comment by kentcdodds** [comment]
You know what would be really cool is to package this up as an npm module you can run with `npx`. Anyone interested in doing that?

**Comment by matt-kinton** [comment]
Oops, your comment @kentcdodds has just notified me that this is a thing and I should have been writing the docs for this. I'd be happy to set it up as a package. Do you want me to setup a package myself, or should it be under the @epic-web group? @epic-web/generate-fallback-fonts or something?

**Comment by kentcdodds** [comment]
@matt-kinton if you're ok accepting the maintenance burden (hopefully very light), then I'm happy with you owning the package :)

**Comment by matt-kinton** [comment]
Okay I've thrown the package together [here](https://github.com/matt-kinton/fontpie-from-css), you can run it using `npx fontpie-from-css <css-file>` 😄

**Comment by kentcdodds** [comment]
Terrific! Thank you for doing that! Would you be interested in adding a reference to this in the docs wherever you think is most appropriate?

**Comment by matt-kinton** [comment]
Sure, I'll try get some free time this week and put it in a pr.

**Comment by kentcdodds** [comment]
While you're at it, I think we should get rid of the custom font within the repo itself (#531). Would you be interested in doing that work while you document how to easily add your own custom font?

**Comment by matt-kinton** [comment]
Manage to get some free time this evening. @kentcdodds the PR is open!
