### ISSUE TITLE
Looks like the repo url is a 404

### ISSUE THREAD

**Issue by JackHowa** [epicweb-dev/epic-stack#3]
- Excited to see this! Good work

<img width="266" alt="Screenshot 2023-05-05 at 9 52 18 AM" src="https://user-images.githubusercontent.com/5950956/236519183-5033cabd-8bff-46d0-9d72-13dbc44b6b0c.png">

**Comment by kentcdodds** [comment]
Coming eventually :)

Hopefully before my talk about this next week at Remix Conf 😅

**Comment by JackHowa** [comment]
yay no worries!
