### ISSUE TITLE
Configure tailwind-merge

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/epic-stack#301]
tailwind-merge needs to be configured to properly merge our custom class names (like text sizes and colors). I looked into it briefly and couldn't figure it out. Help appreciated!

https://github.com/dcastil/tailwind-merge/blob/v1.13.2/docs/configuration.md

**Comment by kentcdodds** [comment]
From @jacobparis: https://discord.com/channels/715220730605731931/1105271172079300630/1122223663656214591

It looks like twMerge does not read your tailwind config so you have to manually configure it whenever you have custom classes

Add this element and you'll see the text-body-lg overrides the text-red because it doesn't know text-body only affects font size

```tsx
<span className={twMerge('text-red-500', 'text-body-lg')}>
  Should be red AND big
</span>
```


I've added this to my tailwind config and import from there instead, which fixes it in this case

```tsx
export const twMerge = extendTailwindMerge({
  classGroups: {
    'font-size': Object.keys(config.theme.extend.fontSize).map(
      key => `text-${key}`,
    ),
  },
})
```

**Comment by jansedlon** [comment]
Isn't it better to use [tailwind-variants](https://www.tailwind-variants.org/) for styling? It includes tw-merge support out of the box. Or do you want to keep styling using inline tailwindcss classes in `className`?

**Comment by kentcdodds** [comment]
Even if we use tailwind-variants, we still need to configure tailwind-merge properly.

**Comment by devneillza** [comment]
Hey @kentcdodds! 

I had to handle this issue in my daily work yesterday and implemented basically what @jacobparis has suggested. 

The only concern with that approach is the bundle size from loading a lot of the Tailwind config into the custom twMerge config (which gets loaded on the client). Perhaps I'll start with a PR and then we can discuss it? Let me know and I'll give it a try!

**Comment by kentcdodds** [comment]
That sounds good to me @devneillza! Thanks!

**Comment by kentcdodds** [comment]
Thanks a lot @devneill!

Your PR has been merged. Here's my test. I just stuck it on the homepage:

```
<div className="text-center">
	<Button className="text-body-sm">Small text</Button>
</div>
```

Before:

![image](https://github.com/epicweb-dev/epic-stack/assets/1500684/f8e6f2c2-a140-4d09-8520-bba91da5ba17)

After:

![image](https://github.com/epicweb-dev/epic-stack/assets/1500684/5d090265-7753-4579-b682-e0678a7ca7e0)

Huzzah!

**Comment by MarinBarac** [comment]
Hi @kentcdodds, I also had the same problem with configuring `twMerge` and your solution helped me a lot. It took me some time before I found pull request that solved this issue, so it would be great if you could mention this issue inside of [pull request](https://github.com/epicweb-dev/epic-stack/pull/367) (**e.g.** closes #301), so that it is easier to find it for other people.

**Comment by kentcdodds** [comment]
I'll try to do better about that!

**Comment by uigywnkiub** [comment]
> From @jacobparis: https://discord.com/channels/715220730605731931/1105271172079300630/1122223663656214591
> 
> It looks like twMerge does not read your tailwind config so you have to manually configure it whenever you have custom classes
> 
> Add this element and you'll see the text-body-lg overrides the text-red because it doesn't know text-body only affects font size
> 
> ```tsx
> <span className={twMerge('text-red-500', 'text-body-lg')}>
>   Should be red AND big
> </span>
> ```
> 
> I've added this to my tailwind config and import from there instead, which fixes it in this case
> 
> ```tsx
> export const twMerge = extendTailwindMerge({
>   classGroups: {
>     'font-size': Object.keys(config.theme.extend.fontSize).map(
>       key => `text-${key}`,
>     ),
>   },
> })
> ```

Refactored version. But it didn't work for me.

```js
export const twMergeTest = extendTailwindMerge({
  extend: {
    classGroups: {
      'font-size': Object.keys(config?.theme?.extend?.fontSize!).map(
        (key) => `text-${key}`,
      ),
    },
  },
})
```

**Comment by tomerzcod7** [comment]
Opening an old issue, anyone knows of a programatic way to achieve this in tailwind v4?
