### ISSUE TITLE
Profile dropdown not working while javascript is disabled

### ISSUE THREAD

**Issue by mohammedzamakhan** [epicweb-dev/epic-stack#310]
The dropdown is not working when javascript is disabled. All the UI components should work even when javascript is disabled. It should work similar to how custom dropdown works on remix.run documentation https://remix.run/docs/en/1.18.1

**Comment by kentcdodds** [comment]
> All the UI components should work even when javascript is disabled.

This is not a requirement of this project. Having things work before JavaScript shows up is a nice-to-have. When JavaScript is not enabled, the dropdown menu takes you to the user profile page where you'll find the same links to things that you would find in the dropdown menu. So the baseline functionality is still there.

If you would like the dropdowns to work the way the remix docs work (with details/summary) then you might reach out to the Radix team and see what they think of it. This particular feature isn't important enough to me to have it work without JavaScript.

One thing to consider is that the approach taken by the Remix docs is not capable of automatic positioning based on the viewport. So if we implemented all dropdowns that way then it's possible the menu would appear off screen. It works in very specific situations, but it's not suitable for general use.
