### ISSUE TITLE
Maybe set fly concurrency to requests instead of connections

### ISSUE THREAD

**Issue by CanRau** [epicweb-dev/epic-stack#317]
https://github.com/epicweb-dev/epic-stack/blob/0c457b279c7839395c7b41682b4d1ca6495de1f5/fly.toml#L27

as in https://github.com/kentcdodds/kentcdodds.com/blob/d0e7ad17700361d4c052584c3143b0932c333bda/fly.toml#L33

also recommended in [fly docs](https://fly.io/docs/reference/configuration/#http_service-concurrency) for web services

**Comment by kentcdodds** [comment]
Sounds solid to me 👍 Wanna make a PR?
