### ISSUE TITLE
automatically check if `build:icons` is needed in development

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/epic-stack#330]
After `git pull` there may be changes to `components/ui` or other changes that require to run `build:icons` again

I wish `npm run dev` will check if `build:icons` is needed before starting `remix dev....`

I don't want to run `npm run setup` after `git pull` since it will remove my test db

**Comment by kentcdodds** [comment]
Yes, this is troubling me as well. I'd like a better solution for building the icons. I'm open to suggestions. I don't want to use hit hooks if we can help it. I think we can do even better. Maybe a part of the dev-server script could add a watcher to the svg folder to build it automatically on changes and when you start it, it checks the modified dates to know whether it needs to be run before starting the server.

**Comment by xHomu** [comment]
This may be a dumb question, but what's the downside of just committing icon.tsx and icon.svg?

**Comment by kentcdodds** [comment]
I just don't like committing generated files because people may not know it's generated and so they'll make a change to the generated files instead of the source for those files and so the next time the file is generated their work is overwritten.

**Comment by kiliman** [comment]
How about adding a `predev` script?
```json
"scripts": {
  "predev": "npm run build:icons",
}
```
I can update `rmx-cli svg-sprite` to be silent if the output hasn't changed.

**Comment by kiliman** [comment]
I pushed `rmx-cli` v0.4.11. This version no longer generates files or outputs to console if generated files are the same as existing. So this should be safe to add to `predev` script.

![image](https://github.com/epicweb-dev/epic-stack/assets/47168/71eb9ded-35b8-448d-a1f3-b99b695f98ca)

**Comment by kentcdodds** [comment]
That may work. But it makes the dev server take longer to start up.

Even if we do that, I think I'd still like to do something where we're watching the `other/svg-icons` directory so we can auto-rebuild whenever a new icon is added.

**Comment by kiliman** [comment]
That's fine. At least you know that you can run it multiple times, and it won't change the output and trigger a rebuild. Either way, you still need to make sure it is executed at least once before running the dev script.

**Comment by xHomu** [comment]
> That may work. But it makes the dev server take longer to start up.

What about using run-p?

**Comment by kiliman** [comment]
I think you need the icons built before the dev server tries to build the app.

**Comment by onemen** [comment]
we can use `predev` to run script that will add watcher to call `npm run build:icons` when `svg-icons` changes
and also run the script if when it start `svg-icons` modified time is later then `app/components/ui` modified time

this code is from Bing AI (untested)

```typescript
import chokidar from 'chokidar';
import execa from 'execa';
import fs from 'fs';

const svgIconsPath = 'other/svg-icons';
const uiPath = 'app/components/ui';

async function runBuildIcons() {
  try {
    await execa('npm', ['run', 'build:icons']);
    console.log('`npm run build:icons` ran successfully');
  } catch (error) {
    console.error('Error running `npm run build:icons`:', error);
  }
}


// Run the script if svg-icons modified time is later than app/components/ui modified time
const svgIconsStat = fs.statSync(svgIconsPath);
const uiStat = fs.statSync(uiPath);
if (svgIconsStat.mtime > uiStat.mtime) {
  await runBuildIcons();
}

// Add watcher to call `npm run build:icons` when `svg-icons` changes
chokidar.watch(svgIconsPath).on('change', async () => {
  await runBuildIcons();
});

```

**Comment by kentcdodds** [comment]
Yeah, that's similar to what I was thinking @onemen, but I think that could be done as part of the `dev-server.js` script.

**Comment by onemen** [comment]
> Yeah, that's similar to what I was thinking @onemen, but I think that could be done as part of the `dev-server.js` script.

If `~/components/ui/icon.tsx` is missing remix run fails before `dev-server.js` starts

**Comment by kentcdodds** [comment]
The `dev-server.js` could check for it first then.

**Comment by onemen** [comment]
`"dev": "remix dev -c \"node ./server/dev-server.js\" --no-restart"`

remix dev call `dev-server.js` but if `~/components/ui/icon.tsx` is missing the process fail before that step

**Comment by kentcdodds** [comment]
Ah, you're right. Hmmm... Yeah, maybe a predev script is the best thing then.

I just wish there were a better way to do this so we didn't have to worry about running another script and the time that adds.

**Comment by courdek** [comment]
What if the predev script only runs if `icon.tsx` doesn't exist and `dev-server.js` handles it otherwise?

**Comment by onemen** [comment]
done in #340
