### ISSUE TITLE
Confirming current password is using `username` provided by the user

### ISSUE THREAD

**Issue by wladiston** [epicweb-dev/epic-stack#335]
There's a bug on the setting new password action. It's using the `username` provided by the user to check if the current password user is valid but if you set a new username at same time as you change the password you get an invalid password error

https://github.com/epicweb-dev/epic-stack/blob/main/app/routes/settings%2B/profile.index.tsx#L73C6-L73C6

**Comment by kentcdodds** [comment]
Nice catch! We should lookup the user by their ID and verify *that* username. Would you be interested in contributing a fix?

**Comment by wladiston** [comment]
Ive already fixed in another repo. Gonna take a break from coding this week and will open a pr when come back
