### ISSUE TITLE
build-icons script does not always detect new icons

### ISSUE THREAD

**Issue by DigitalGoldfish** [epicweb-dev/epic-stack#349]
This is the code the script uses to determine if the icon files should be updated:
```
const spriteUpToDate = iconNames.every(name =>
		currentSprite.includes(name),
	);
const typesUpToDate = iconNames.every(name => currentTypes.includes(name));
```

This has multiple issues:
 - If a  new icon is a substring of an already existing icon it doesn't get added (e.g. if double-arrow-left already exist arrow-left doesn't get added)
 - If an icon is modified the modified svg will not be copied into the sprite.svg
 - Removed icons are not removed from the sprite.svg/name.d.ts

The first issue could be fixed by modifying the checks like this 
```
const spriteUpToDate = iconNames.every(name =>
		currentSprite.includes(`id="${name}"`),
	);
const typesUpToDate = iconNames.every(name => currentTypes.includes(`"${name}"`));
```

**Comment by kiliman** [comment]
In `rmx-cli`, I compare the "generated" file with the existing file, if present, and will not overwrite it. This ensures that any changes will update the file, but will not trigger file watchers with false positives.

**Comment by kentcdodds** [comment]
This is fixed.
