### ISSUE TITLE
Implement Docusauros for the docs

### ISSUE THREAD

**Issue by JeanPaiva** [epicweb-dev/epic-stack#352]
I was reading the docs but the experience is not the best, I was thinking that maybe we could host the docs live, something like [Docusaurus](https://docusaurus.io/) which may improve that experience, or any other similar solution.

If this is something worth working on I'm happy to try it as my first contribution to the project.

**Comment by kentcdodds** [comment]
I'm definitely planning on making a docs site eventually. It'll be completely custom. I've used docusaurus before and it won't quite do what I envision for the docs. Thanks though!
