### ISSUE TITLE
UI glitch when opening user profile

### ISSUE THREAD

**Issue by kandros** [epicweb-dev/epic-stack#354]
When clicking on a user from the list at http://localhost:3000/users, I've noticed a glitch that makes the page scroll to the top before the navigation.

~~I'm not yet familiar enough with remix and the codebase to fix it myself at the moment, but I figured out it's caused by the autofocus of in search bar input https://github.com/epicweb-dev/epic-stack/blob/main/app/components/search-bar.tsx#L46~~ opened PR

Here's a video with slow motion frames that shows it
https://github.com/epicweb-dev/epic-stack/assets/4562878/6be1e0cb-57de-4c42-b773-821e2c8c5fa5

**Comment by lewisblackburn** [comment]
This happens when opening dialogues and dropdown menus too

**Comment by kentcdodds** [comment]
I've removed the dev tools temporarily until this gets fixed.
