### ISSUE TITLE
Remix DevTools reset my state.

### ISSUE THREAD

**Issue by hakimLyon** [epicweb-dev/epic-stack#356]
https://github.com/epicweb-dev/epic-stack/assets/64654633/96546309-0887-4873-9dae-cedd134d61cb

when I remove this part from the `entry.server.ts` file:
```ts
const context =
	process.env.NODE_ENV === 'development'
		? await import('remix-development-tools').then(
				({ initRouteBoundariesServer }) =>
					initRouteBoundariesServer(remixContext),
		  )
		: remixContext
```
And also this part from the `entry.client.ts` file:
```ts
if (process.env.NODE_ENV === 'development') {
	import('remix-development-tools').then(({ initRouteBoundariesClient }) => {
		initRouteBoundariesClient()
		startTransition(() => {
			hydrateRoot(document, <RemixBrowser />)
		})
	})
 
```
its works.
# Expected result
https://github.com/epicweb-dev/epic-stack/assets/64654633/c8b801e7-3887-4df8-b4a5-4c4c7260d577

**Comment by kentcdodds** [comment]
I've removed the dev tools temporarily until this gets fixed.
