### ISSUE TITLE
Speed up dev server startup

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/epic-stack#363]
I don't know what's making the dev server take multiple seconds to start up, but I want it to be *much* faster (instant).

This is open for anyone to troubleshoot.

**Comment by onemen** [comment]
epic-stack server/index.js time is only 25ms

You should probably look at Remix.
When it log `info built (3.3s)` the actual time is about 2 seconds more.

**Comment by kentcdodds** [comment]
I wonder if it would be possible to do some things in parallel. Maybe the server can start accepting traffic but hold off on responding until the build is ready? That would at least make it easier during development to start opening the app immediately even if it doesn't respond right away.

**Comment by vinstah** [comment]
There is a dev server warning about totp being ESM now, unsure if related. dev server also does pre-build step which might only need to happen once, not everytime a dev server is started

**Comment by kentcdodds** [comment]
That's a false warning. The Remix team is going to be removing it in the next version.

**Comment by vinstah** [comment]
this seems to be slow boot when using express

**Comment by kentcdodds** [comment]
I wouldn't mind switching from express. But we'd need to support all the things we do in express with whatever else we use.
