### ISSUE TITLE
Add honeypot

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/epic-stack#371]
Just for those annoying bots

**Comment by kentcdodds** [comment]
My current thoughts:

I already have a honeypot on [kentcdodds.com/login](https://kentcdodds.com/login). It has been effective. Lots of honeypot implementations involve `display: none !important` as an inline style. I think this is too low-hanging fruit for bot writers to not handle. So instead, we'll implement a custom CSS class that would probably not be handled by default. And for similar reasons, instead of `display: none` it will use `opacity: 0; position: absolute; top: 0; left: 0; height: 0; width: 0; z-index: -1;` with a `tabindex="-1"` and `autocomplete="nope"` on the field. We'll want to also test it with screen readers to ensure those fields are not reachable by assistive technologies.

We'll build out a simple component/server-util combo to make doing this as easy as possible and then implement it on all publicly accessible forms.

To be clear, the objective of a honeypot is not to avoid a targeted attack, but to general attacks. So it doesn't have to be very sophisticated.

Any ideas or suggestions are welcome.

**Comment by kentcdodds** [comment]
I think we'll probably use `@apply sr-only` for our class name actually. I don't want to use the class name `sr-only` itself because bots may have encoded that into their functionality already.

Another thought is I want to make certain screen readers won't read any of the content. I'm pretty sure that `tabindex="-1"` will do it, but I'm not positive of this...

**Comment by EisenbergEffect** [comment]
You might find this helpful:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden

**Comment by kentcdodds** [comment]
Thanks for the suggestion @EisenbergEffect. I wonder if spam bots are sophisticated enough to ignore fields that have that attribute though.

**Comment by EisenbergEffect** [comment]
Yeah, I'm not sure. And it's probably not exactly what you want anyways since it's not supposed to be used on interactive elements. But I thought I'd drop the link here just in case that or some of its related links were helpful. FYI I don't think you'll solve the accessibility tree issue by just setting `tebindex="-1"`. That will remove the element from the keyboard navigation flow but shouldn't remove it from the accessibility tree.

**Comment by sean-roberts** [comment]
`getComputedStyle` is pretty easy to use to find any given element's own styling and thus width/height would be easy to check for if it's `0` - just as easy as checking for display. 

You might consider using a parent element that can force it to be invisible but the input element itself doesn't have any unique styling. The downside there would be if they did all of the checks on the input ancestors, but this is starting to get closer to targetted attack. 

By nature though, you're developing a pattern that won't be seen as a "targeted" attack (unique to your implementation), it will become a general attack for epic-stack users. So, the closer you can come to something dynamic, the better (probably later problem to make it more sophisticated).

**Comment by kentcdodds** [comment]
Thanks @sean-roberts,

I wish I had a sense for what spam bots actually do. I have a pretty basic honeypot on my own site and it takes care of a lot of my spam. I doubt these tools actually run a real browser and evaluate enough of the page to actually run `getComputedStyle`, so I don't think that's necessary.

**Comment by gabbanaesteban** [comment]
I loved this implementation of https://github.com/spatie/laravel-honeypot

Easy to use, just drop the component and thats it.

Lots of uses cases covered and new strategies to trick bots like intercepting requests submitted faster than the encrypted timestamp set by you.

**Comment by kentcdodds** [comment]
That looks great! Do you know of any deployed example implementation I can look at? I'm not very good at understanding php code 😅

**Comment by r4pt0s** [comment]
Hi @kentcdodds,

No need for php knowledge here.
I think the blade template shows it good. It's basically the same what you suggested.
But instead of setting the input itself display none and aria-*, it is wrapped into a div which does it.

https://github.com/spatie/laravel-honeypot/blob/main/resources/views/honeypotFormFields.blade.php

**Comment by sergiodxa** [comment]
Looks like at the HTML it renders two inputs like this

```tsx
<div
  id={`${nameFieldName}_wrap`}
  style={{ display: "none" }}
  aria-hidden="true"
>
  <input
    id={nameFieldName}
    name={nameFieldName}
    type="text"
    defaultValue=""
    autoComplete="off"
    tabindex="-1"
  />
  <input
    name={validFromFieldName}
    type="text"
    value={encryptedValidFrom}
    autoComplete="off"
    tabindex="-1"
  />
</div>
```

There's a `Honeypot` with a `nameFieldName` which based on a config (`randomize_name_field_name`) it can either return `name_field_name` value from the config or use that combined with a random string (`${configValue}_${randomString}`).

There's an `enabled` config to let you enabled/disabled this package.

There's also a `valid_from_field_name` config used for the second input, and a `amount_of_seconds` config used to calculate `Date.now() + amount_of_seconds` and determine how long this will be valid.

This `validFrom` value is later encrypted on another method `encryptedValidFrom` and that's used as the value of the second input.

There's then some kind of middleware (`ProtectAgainstSpam`) that ignores any non POST request, and if it's POST it will check the body using the `SpamProtection` class.

The `SpamProtection` class has a `check` method, it will bail out if the `enabled` config is false.

If enabled it will get the request body and read the value of `name_field_name`. If `randomize_name_field_name` is enabled it use the `name_field_name` to find what field of the request body starts with that value, something like this:

```ts
function getRandomizedNameFieldName(nameFieldName, formData) {
  for (let key of formData.keys()) {
    if (!key.startsWith(nameFieldName)) continue;
    return key;
  }
}
```

Once it knows the key, it checks if it needs to validate the honeyput input, this is also configured with the `honeypot_fields_required_for_all_forms` option, if that's sets to true it will always validate, if it's false it will check if the request body has either the nameFieldName or a `validFromFieldName` (the timestamp).

Then it checks if the request has `nameFieldName`, if it doesn't it will throw an `SpamException`, this will ensure the input is always sent (I imagine to prevent direct POST requests).

Then it will get the actual value, and if it's not empty it will also throw `SpamException`.

Then if `valid_from_timestamp` is not configured it will end. If it's configured it will get the `validFromFieldName` value (previous check if the field exists on the body like before) and parse the encrypted time (default to null if it fails to parse it).

Finally, if there's no time or if the time is in the future it will throw an `SpamException`.

Going back to the middleware, if a `SpamException` was thrown, it will dispatch an `SpamDetectedEvent` with the request data and call the spam responder, the spam responder is class with an empty `respond` method with the signature `(request: Request, next: NextFunction)` so I imagine it's a middleware and can be overwritten at the app level.

---

I'm not sure if it was easy to follow, the code in TS would look something like this

```ts
interface Config {
  enabled?: boolean;
  randomize_name_field_name: boolean;
  name_field_name: string;
  valid_from_field_name: string;
  amount_of_seconds: number;
  honeypot_fields_required_for_all_forms: boolean;
}

class SpamError extends Error {}
class TimestampError extends Error {}

class Honeypot {
  constructor(protected config: Config) {}

  unrandomizedNameFieldName() {
    return this.config.name_field_name;
  }

  nameFieldName(): string {
    let nameFieldName = this.unrandomizedNameFieldName();
    if (this.config.randomize_name_field_name) {
      nameFieldName = `${nameFieldName}_${this.randomValue()}`;
    }
  }

  enabled() {
    return this.config.enabled;
  }

  validFromFieldName() {
    return this.config.valid_from_field_name;
  }

  validFrom() {
    return Date.now() + this.config.amount_of_seconds;
  }

  encryptedValidFrom() {
    return this.encrypt(this.validFrom());
  }

  private randomValue() {
    return crypto
      .getRandomValues(new Uint8Array(16))
      .reduce((p, i) => p + (i % 32).toString(32), "");
  }

  private encrypt() {
    // implementation missing
  }
}

class ProtectAgainstSpam {
  constructor(protected spamResponder: SpamResponder) {}

  async handle(request: Request, next: NextFunction) {
    if (request.method !== "POST") {
      return next();
    }

    try {
      SpamProtection.check(await request.formData());
      return next(request);
    } catch (exception) {
      if (exception instanceof SpamError) {
        // dispatch event here
        return this.spamResponder.respond(request, next);
      }
      throw exception; // re-throw unknown exception
    }
  }
}

class SpamResponder {
  respond(request: Request, next: NextFunction) {}
}

class SpamProtection {
  static check(formData: FormData) {
    if (!config("honeypot.enabled")) return;

    let nameFieldName = config("honeypot.name_field_name");

    if (config("honeypot.randomize_name_field_name")) {
      nameFieldName = this.getRandomizedNameFieldName(nameFieldName, formData);
    }

    if (!this.shouldCheckHoneypot(formData, nameFieldName)) return;

    if (!formData.has(nameFieldName)) throw new SpamError();

    let honeypotValue = formData.get(nameFieldName);

    if (honeypotValue !== "") throw new SpamError();

    if (!config("honeypot.valid_from_timestamp")) return;

    let validFrom = formData.get(config("honeypot.valid_from_field_name"));

    if (!validFrom) throw new SpamError();

    let time = null;
    try {
      time = new EncryptedTime(validFrom);
    } catch {}

    if (!time || time.isFuture()) throw new SpamError();
  }

  protected static getRandomizedNameFieldName(
    nameFieldName: string,
    formData: FormData,
  ): string | undefined {
    for (let key of formData.keys()) {
      if (!key.startsWith(nameFieldName)) continue;
      return key;
    }
  }

  protected static shouldCheckHoneypot(
    formData: FormData,
    nameFieldName?: string,
  ): boolean {
    // this config function should access the global app config somehow
    if (config("honeypot.honeypot_fields_required_for_all_forms")) return true;

    return (
      formData.has(nameFieldName) ||
      formData.has(config("honeypot.valid_from_field_name"))
    );
  }
}

class EncryptedTime {
  protected date: Date;

  constructor(protected encryptedTime: string) {
    try {
      this.date = new Date(this.decrypt(encryptedTime));
    } catch {
      throw TimestampError();
    }

    if (!this.isValidTimeStamp(this.date.getTime())) throw TimestampError();
  }

  isFuture() {
    return this.timestamp() > Date.now();
  }

  protected isValidTimeStamp(timestampp: number) {
    if (timestampp <= 0) return false;
    if (timestampp >= Number.MAX_SAFE_INTEGER) return false;
    return true;
  }
}
```

I think this is it the core of how it works. There's some parts that depends on Laravel things too but this is basically the core.

**Comment by sergiodxa** [comment]
I could probably add this to Remix Utils itself in the future 🤔

**Comment by kentcdodds** [comment]
Wow! Thanks for that Sergio! I definitely feel like remix-utils would be a great place for this.

**Comment by kentcdodds** [comment]
This is done
