### ISSUE TITLE
Protect the delete note action

### ISSUE THREAD

**Issue by darlantc** [epicweb-dev/epic-stack#395]
I was testing the last version of epic-stack and noticed that I can delete other users notes.

![screenshot 2023-08-19 at 11 41 33@2x](https://github.com/epicweb-dev/epic-stack/assets/5101009/a94e094b-11c3-4bb1-8a57-26f5a285ec07)

**Comment by kentcdodds** [comment]
You're logged in as Kody who is an admin user and has permission to delete any notes: https://github.com/epicweb-dev/epic-stack/blob/b1f450f9c25d3f3d9efb066a1c23ef379fb03ac2/app/routes/users%2B/%24username_%2B/notes.%24noteId.tsx#L90-L93
