### ISSUE TITLE
User search not working as intened

### ISSUE THREAD

**Issue by arpitdalal** [epicweb-dev/epic-stack#414]
The input lags behind 1 search. Please see the video to see this issue.

https://github.com/epicweb-dev/epic-stack/assets/61059807/9946cedf-e1f7-4230-94ea-04413a6db971

I couldn't reproduce this issue in a [codesandbox](https://codesandbox.io/p/sandbox/youthful-galileo-zfg48z)
I don't know what's causing it. I've tried creating a new search box, removing debounce, using a fetcher, etc but nothing solved. Only using HTML `form` solved it as it refreshes the whole page but that isn't a good UX either.

**Comment by kentcdodds** [comment]
Thanks for reporting this @arpitdalal.

This is the last straw for me with the dev tools. I'm tired of the issues that keep coming up as a result of them. I've removed them and don't plan on adding them back. Very disappointing.

**Comment by arpitdalal** [comment]
Too bad it's remix dev tools. Is there an issue opened on its repo for this behaviour?

**Comment by kentcdodds** [comment]
Not that I know of. Sorry.

**Comment by AlemTuzlak** [comment]
> Too bad it's remix dev tools. Is there an issue opened on its repo for this behaviour?

will look into this

**Comment by AlemTuzlak** [comment]
@arpitdalal the issue has been resolved with v3!
