### ISSUE TITLE
Authentication not working for me after changes in schema

### ISSUE THREAD

**Issue by felixyeboah** [epicweb-dev/epic-stack#426]
I made changes to the Prisma schema replacing the username on the User model with phoneNumber, and made sure to make every necessary change that would affect the app. 

Run `prisma migrate dev` but the session keeps throwing this error `Invalid `prisma.session.create()` invocation: An operation failed because it depends on one or more records that were required but not found. Expected 1 records to be connected, found only 0.`. I added back the username but this time made it optional and ran the migrations again. This time, it seems to run in development but still throws that error in production. Anyone to help me out? I am running out of deadline :(

**Comment by ngtrthinh169TPC** [comment]
I think this is a specific problem on your prisma model and not related to this stack, so it is unlikely that people will help you here.
I'd suggest you bringing this question to https://stackoverflow.com/ and provide more context like your model file and session file, since that would be a more suitable place to ask things like this.

**Comment by 8an3** [comment]
I'm having the same issue. Runs fine on dev server locally, but when running in production on fly, it seems like the session can't be created. It's still writing to the database. A user is created in the db but gets hung up on onboarding. Looking into it now, ill post if  i have a resolution

**Comment by felixyeboah** [comment]
> I'm having the same issue. Runs fine on dev server locally, but when running in production on fly, it seems like the session can't be created. It's still writing to the database. A user is created in the db but gets hung up on onboarding. Looking into it now, ill post if i have a resolution

i thought i made a mistake somewhere, i have tried looking into this several times and ended up changing the whole project idea but i'd be happy if you share the solutions you find.

**Comment by kentcdodds** [comment]
I'm afraid there's no actionable information in this issue so I'm going to have to close it

**Comment by andrecasal** [comment]
If you guys decide to open an issue on StackOverflow, I'd be happy to take a look 😉
