### ISSUE TITLE
Mobile login issues

### ISSUE THREAD

**Issue by dchadcluff** [epicweb-dev/epic-stack#427]
I wanted to make the community aware of an issue that my users discovered. It didn't become apparent until users started trying to log in via mobile devices and the login would fail with an invalid username or password error.

The issue is that the username field is case sensitive, when on a desktop, it defaults to lower case, so you put in the username and all is well. But on mobile it generally defaults to autocapitalizing the first letter of the word, and because the field has a className of lowercase it displays as if it's all lowercase, but what is sent to the server is an uppercase first letter and everything else lowercase. This means it doesn't match the user in the database and authentication fails.

Solutions include removing the className, running toLowerCase on all newly created usernames and every time a user logs in, or possibly altering the verifyUserPassword method to find the user with case insensitive mode.

**Comment by kentcdodds** [comment]
Thanks! I thought we already do transform the username to lowercase automatically: https://github.com/epicweb-dev/epic-stack/blob/main/app/utils/user-validation.ts#L11


Is there a place where this isn't being applied?

**Comment by dchadcluff** [comment]
It looks like that is transforming the username when saving to the database, but when performing a login it is not being transformed.

If you check the auth.server.ts function verifyUserPassword
````
export async function verifyUserPassword(
	where: Pick<User, 'username'> | Pick<User, 'id'>,
	password: Password['hash'],
) {
	const userWithPassword = await prisma.user.findUnique({
		where,
		select: { id: true, password: { select: { hash: true } } },
	})
//console out what the username is
console.log('WHERE!!!, where)
...
````
The output is 
WHERE!!! { username: 'Ccluff' }

This despite the fact that the login field displays: ccluff

**Comment by kentcdodds** [comment]
Are you sure you were doing the same thing in your version of the app as what's in the epic stack currently? Because the way that the login is set up the parsing should happen before that function is called, which would result in lowercasing properly.

**Comment by dchadcluff** [comment]
I started the project 4 weeks ago and haven't made any changes to the authentication flow. It's possible changes have been made since that time that correct the flow. I can try and start a fresh project to see if I can replicate the issue with the latest if that would help.

I can confirm that my user-validation.ts matches the current version exactly.

**Comment by kentcdodds** [comment]
Interesting. Well, the code looks ok to me and I'm not able to reproduce your issue (though I can verify that you can type uppercase characters into the field which is fine). Let me know if you figure out what the issue is.

**Comment by dchadcluff** [comment]
I tracked it down, it was corrected by a pretty big refactor of login stuff (among many other things!) in commit 5cb5110 

app/utils/auth.server.ts

```
const signInForm = z.object({
	username: z.string(),
	password: z.string(),
})

authenticator.use(
	new FormStrategy(async ({ form }) => {
		const { username, password } = signInForm.parse({
			username: form.get('username'),
			password: form.get('password'),
		})

		const user = await verifyUserPassword({ username }, password)
```

**Comment by kentcdodds** [comment]
Oh good! Thanks for tracking that down.
