### ISSUE TITLE
Use CUID2 instead of CUID?

### ISSUE THREAD

**Issue by RIP21** [epicweb-dev/epic-stack#436]
CUID is officially deprecated
https://github.com/paralleldrive/cuid

**Comment by estubmo** [comment]
How about NanoId?
This post has a nice comparison: https://dev.to/harshhhdev/uuidguid-cuid-nanoid-whats-the-difference-5dj1

**Comment by RIP21** [comment]
There is cuid2 BTW.

**Comment by kentcdodds** [comment]
I'm not using [`paralleldrive/cuid`](https://github.com/paralleldrive/cuid), I'm using [`paralleldrive/cuid2`](https://github.com/paralleldrive/cuid2) :)

You almost gave me a heart attack 😆 Thanks anyway!

**Comment by kentcdodds** [comment]
As for Nanold, our use cases are pretty simple so cuid2 is good for us :)

**Comment by RIP21** [comment]
Sorry just decision docs talk about CUID and not the CUID2, so I guessed that CUID 1 was used.
