### ISSUE TITLE
Node.JS 16 is now end of life

### ISSUE THREAD

**Issue by ahmeducf** [epicweb-dev/epic-stack#438]
Version 16 of Node.JS is now end of life so you can delete it from the list of maintained versions in [021-node-version.md](https://github.com/epicweb-dev/epic-stack/blob/main/docs/decisions/021-node-version.md) doc.

Check Node.JS Twitter's account [Tweet](https://twitter.com/nodejs/status/1701309614263001569).

**Comment by kentcdodds** [comment]
Thanks for the PR. Replied there.
