### ISSUE TITLE
Infinite refresh

### ISSUE THREAD

**Issue by andrecasal** [epicweb-dev/epic-stack#444]
I've got this infinite refresh bug, which I suspect is either from ClientHints or the new version 117.0.5938.62 of Chrome (or both).

I haven't figured out how to reproduce the issue reliably on localhost yet, but here's how to reproduce it in production:
1. Open [some page](https://andrecasal.com/articles/fluid-typography-sizing-with-modular-scales) on my website
2. Quit Chrome
3. Reopen Chrome
4. Watch the page infinitely reload

Then go to some other page and it just works 🤷‍♂️

Leaving this here to see if someone else is bumping into the same issue, which I'll try and resolve today.

Video's too large, so I uploaded it to YouTube. [Here](https://youtu.be/3e25fFwMplQ) it is.

**Comment by kentcdodds** [comment]
I'm afraid I can't reproduce this myself. Can you reproduce it on https://www.epicstack.dev? Maybe it's something about your site?

**Comment by andrecasal** [comment]
This is hard to reproduce. I can't quite understand when this happens. My strategy is to wait for it to happen again to try and investigate it.

**Comment by andrecasal** [comment]
It's related to the page-specific theme issue.

**Comment by andrecasal** [comment]
I see this was fixed with 85d29f63b0d866638192a0f18650dfccf27db9ba
