### ISSUE TITLE
Add passkeys/WebAuthn support

### ISSUE THREAD

**Issue by MichaelDeBoey** [epicweb-dev/epic-stack#448]
Just like GitHub ([and many others](https://passkeys.directory)) have done

- https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API
- https://www.w3.org/TR/webauthn-2
- https://fidoalliance.org/fido2-2/fido2-web-authentication-webauthn
- https://passkeys.dev
- https://simplewebauthn.dev
- https://github.blog/2023-07-12-introducing-passwordless-authentication-on-github-com

**Comment by kentcdodds** [comment]
Yep, this is definitely planned. I'm planning on using [remix-auth-webauthn](https://github.com/alexanderson1993/remix-auth-webauthn) by @alexanderson1993. Just need to find some time to do that.

Anyone can feel free to put together an example. That would help a lot.

**Comment by rperon** [comment]
Hello,

I started an example that you can checkout there : https://github.com/rperon/epic-stack-with-passkeys/pull/1

For now this is not a very good implementation, I have to cheat with the Submission object that we get from Zod. I'm thinking that we need 2 zod schemas to handle the absence of passwords... Or you might have a better idea, of how I can do that.

The interesting part are:
- `webauthn.server.ts` for the WebAuthN Strategy implementation
- `onboarding.tsx` and `login.tsx` and the action function were I'm cheating to get this working ... ^^

**Comment by kentcdodds** [comment]
What if we add a new route: `/onboarding/passkey` and then the existing password onboarding flow can go in `/app/routes/auth+/onboarding.index.tsx` and `/app/routes/auth+/onboarding.tsx` can be a simpler route that just renders an Outlet. That way these flows can be pretty separate. Then the user can choose between password and passkey by clicking a link between the two routes.

**Comment by kentcdodds** [comment]
I'm talking about the onboarding page. The `/verify` page would have to come after they provide the passkey

**Comment by kentcdodds** [comment]
This is great! Thank you for putting that work in!
