### ISSUE TITLE
Code editors like VSCode are not using by default project prettier config

### ISSUE THREAD

**Issue by jordisantamaria** [epicweb-dev/epic-stack#457]
Hi, I'm working on a project with this template and I noticed all members are having the same problem, with using the formating of code editors like VSCode, for example, the format on save, it's not formatting the code following the configuration defined on .prettierrc.cjs, it's using the default configuration of every member on VSCode.

I think the problem happens because this project is using .prettierrc.cjs instead of .prettierrc file.

It's a minor problem, but it would be great if It could be fixed, thanks.

**Comment by jordisantamaria** [comment]
I mean, right now if you use the command `npm run format`, It's formatting the code right following prettier configuration defined on .prettierrc.cjs

What I wanted to say, is that It could be cool to configure the project, so when you run format code with VSCode, code get formated with the rules defined on .prettierrc.cjs instead of the default rules of VSCode.

In all the other projects I worked before, VSCode was always taking the configuration of the project to format the code, but it's not working like this on this project.

**Comment by kentcdodds** [comment]
And what I'm saying is my experience is different. It's working for me. And nobody else has complained about this either. So it sounds like there may be an issue with your editor configuration.

**Comment by jordisantamaria** [comment]
I'm sorry seems it's working, i guess I was confused by how it was formatting the code.

**Comment by kentcdodds** [comment]
I'm glad to hear it's working!
