### ISSUE TITLE
Redirecting twice when encountered double trailing slash

### ISSUE THREAD

**Issue by nichtsam** [epicweb-dev/epic-stack#463]
I'm not sure if it is a case that's supposed to be tackled,\
but since the code deals with multiple slashes, I'm guessing that it is.\

when entered url for example `https://www.epicweb.dev/epic-stack//`,\
it redirects to `https://www.epicweb.dev/epic-stack/` first,\
and then another to `https://www.epicweb.dev/epic-stack`.

https://github.com/epicweb-dev/epic-stack/blob/fc96c59ddd889419634224e10f4a591ad0448b84/server/index.ts#L62-L72

**Comment by kentcdodds** [comment]
Hi @nichtsam!

> since the code deals with multiple slashes

I don't think the code does deal with this. It only deals with a single trailing slash.

In what situation do you have a link that ends with two slashes?

How is multiple redirects a real-world issue?

**Comment by nichtsam** [comment]
Hi @kentcdodds!

I don't have much knowledge on url handling, maybe I'm mistaken.\
I thought that `safepath` handles two thing, `.slice(0, -1)` removes the trailing slash, and `.replace(/\/+/g, '/')` replacing all repeating slashes with single slash.\
Personally I don't meet these issue, it just felt off when I was playing with it.

**Comment by kentcdodds** [comment]
Yeah, I don't think this is worth doing anything special for. Thanks anyway!
