### ISSUE TITLE
Errors Not Captured in Sentry with Remix 2.0.1 

### ISSUE THREAD

**Issue by MoSattler** [epicweb-dev/epic-stack#468]
I encountered an issue where errors were not being reported to Sentry while using the vanilla Epic Stack setup. To resolve this, I followed [this manual setup guide provided by Sentry](https://docs.sentry.io/platforms/javascript/guides/remix/manual-setup). I implemented additional code in the [error boundary](https://docs.sentry.io/platforms/javascript/guides/remix/manual-setup/?original_referrer=https%3A%2F%2Fwww.google.com%2F#v2-errorboundary) and in the [server entry](https://docs.sentry.io/platforms/javascript/guides/remix/manual-setup/?original_referrer=https%3A%2F%2Fwww.google.com%2F#v2-server-side-errors) as suggested in the guide, which fixed it. 

Relevant dependencies:
```json
{
  "dependencies": {
    "@remix-run/css-bundle": "2.0.1",
    "@remix-run/express": "2.0.1",
    "@remix-run/node": "2.0.1",
    "@remix-run/react": "2.0.1",
    "@remix-run/server-runtime": "2.0.1",
    "@sentry/remix": "^7.72.0",
  },
  "devDependencies": {
    "@remix-run/dev": "^2.0.1",
    "@remix-run/eslint-config": "^2.0.1",
    "@remix-run/serve": "^2.0.1",
    "@remix-run/testing": "^2.0.1",
  }
}

```

**Comment by kentcdodds** [comment]
Thanks for this!

I'd really like to look at how we can improve the sentry setup instructions based on the new fly support: https://fly.io/docs/reference/sentry/

Any advice, tips, and pull requests are welcome!

**Comment by andrecasal** [comment]
As far as I can see, the advantage to Fly's Sentry integration is automatic instrumentation, a year's worth of Team Plan, and the `fly apps errors` command. 

Only `Ruby on Rails` gets automatic instrumentation for now, so we still have to instrument our application manually. I assume we should expect them to add Remix v2 eventually.

**Comment by kentcdodds** [comment]
@MoSattler would you be interested in making a pull request for the changes you made?

**Comment by kentcdodds** [comment]
I added a few bits to the epic stack to improve reporting and it's working better, but I'm not sure I got everything. Could you let me know what all you did?

**Comment by kentcdodds** [comment]
Pretty sure I've got it all now.
