### ISSUE TITLE
[DOCS] Sqlite file path out of date

### ISSUE THREAD

**Issue by WillSmithTE** [epicweb-dev/epic-stack#476]
It seems like the file path in the [docs](https://github.com/epicweb-dev/epic-stack/blob/main/docs/deployment.md) is out of data.

Docs: /data/sqlite.db
Actual: /litefs/data/sqlite.db

I'm new to sqlite and fly so could be missing something here.

**Comment by kentcdodds** [comment]
It's kinda funny actually. So the file in `/litefs/data/sqlite.db` is a fake file that LiteFS manages. Any changes to that get auto-propogated to all other databases. The `/data` directory is where the real data lives. But you're right, the docs are out of date and unclear. I'll fix that.

**Comment by kentcdodds** [comment]
Fixed: https://github.com/epicweb-dev/epic-stack/blob/main/docs/database.md

**Comment by WillSmithTE** [comment]
Cool makes sense! Just to confirm, the docs now say `/litefs/sqlite.db`, but at least on my apps, it looks like `/litefs/data/sqlite.db`. Again not 100% sure what I'm doing here, could just be me, just wanted to triple-check it wasn't a typo.

**Comment by kentcdodds** [comment]
Yep, my bad. Fixed! Thank you :)
