### ISSUE TITLE
[Docs] Documentation / examples of backing up database

### ISSUE THREAD

**Issue by matt-winfield** [epicweb-dev/epic-stack#480]
Backups of databases are important. It would be great to have some documentation about how to do this:
1. Manually backing up
2. Automatically saving a backup (e.g. to an S3 bucket) daily or as part of deployment pipeline
3. Restoring from a backup

**Comment by kentcdodds** [comment]
Yes! Definitely need to have a docs section that points people to https://fly.io/docs/litefs/cloud-backups/

I'm hoping to record a video demonstrating how to do this as well
