### ISSUE TITLE
Fonts not loading properly.

### ISSUE THREAD

**Issue by acollazomayer** [epicweb-dev/epic-stack#486]
I just installed the template, and the default fonts are not loading properly. 

The only thing that I did was to ignore deployment configuration when installing the template. Any ideas how to fix it?

**Comment by acollazomayer** [comment]
Removing the font family from the extended configuration in the tailwind.config.ts file seems to fix it.

**Comment by kentcdodds** [comment]
Hmmm.... Seems to be working in production: https://www.epicstack.dev

**Comment by acollazomayer** [comment]
@kentcdodds I re-installed everything and looks like its working now... Maybe a random issue. Close it for now.
