### ISSUE TITLE
"Oh no! Failed to commit changes from remix.init script."

### ISSUE THREAD

**Issue by RangerCoder99** [epicweb-dev/epic-stack#496]
I keep getting this error during installation:
`"Oh no! Failed to commit changes from remix.init script."`

I'm on Windows 11, using Node.js 18.18.2 and NPM 10.2.0.  Not sure why it failed to commit changes from the remix.init script.

**Comment by kentcdodds** [comment]
Hi @RangerCoder99!

Yeah, I've reproduced this myself. I think this may be an issue in the Remix CLI, but I haven't had time to investigate.

For now, the workaround is simple. All you're missing out on is Remix doing this for you:

```
git init
git add .
git commit -am 'initial commit'
```

**Comment by kentcdodds** [comment]
I'm not sure what's up with the Remix CLI, but now I've got `npx create-epic-app@latest` which will call into the Remix CLI and disables the git init step so this won't be a problem (git init must be done manually now)
