### ISSUE TITLE
useSpinDelay does not seem to do anything anymore

### ISSUE THREAD

**Issue by EugenEistrach** [epicweb-dev/epic-stack#499]
I noticed that I see flashing when I click on the save changes button.
I can reproduce it with clean install: 

1. npx create-remix@latest --install --init-script --git-init --template epicweb-dev/epic-stack
2. cd into project
3. npm run dev
4. login
5. go to edit profile and click "Save changes"

Expected
It should not flash

Actual
It flashes

Atleast if I compare the behaviour to the live deployed site (https://www.epicstack.dev), it behaves differently

**Comment by kentcdodds** [comment]
Hmmm... I'm not able to reproduce this issue. It seems to be behaving as expected for me 🤔 Sorry!
