### ISSUE TITLE
Note of any user can be viewed if you know the username

### ISSUE THREAD

**Issue by kasperpeulen** [epicweb-dev/epic-stack#513]
See those lines:

https://github.com/epicweb-dev/epic-stack/blob/a55f6dc3185f6ed906ead257ba3e8a0b41855026/app/routes/users%2B/%24username.tsx#L11-L28

Even if you are not logged in, you can view notes of any user:

![image](https://github.com/epicweb-dev/epic-stack/assets/1035299/69e0345b-b793-4418-ba9d-11c9a0045def)

**Comment by kentcdodds** [comment]
Correct, that's a feature. In the notes app the notes are intended to be public

**Comment by kasperpeulen** [comment]
Ah, okay!
