### ISSUE TITLE
Why confetti?

### ISSUE THREAD

**Issue by fdietze** [epicweb-dev/epic-stack#530]
I'm starting a new project and removing things I don't need from the template. I just encountered the confetti integration with its own dependency. Seemed unnecessary to me, and I guess it will be removed in every project which builds on this stack.

Was there a good reason to add it to the template?

**Comment by kentcdodds** [comment]
You're right. It violates the [guiding principle](https://github.com/epicweb-dev/epic-stack/blob/main/docs/guiding-principles.md) of "Include Only Most Common Use Cases." We should probably just remove that and move it to an example.

Would you be interested in making a PR to remove it?

**Comment by fdietze** [comment]
> Would you be interested in making a PR to remove it?

I will, if I decide to continue with epic stack. Right now, I'm a bit disillusioned by how much time it takes to remove stuff I don't need...

**Comment by kentcdodds** [comment]
Well, you're either removing stuff you don't need or creating all the stuff you do. I think it takes more work to create the new stuff than remove the stuff you don't need, but everyone's gotta make that evaluation for themselves :) I've pushed a change to remove the confetti though. Cheers :D

**Comment by sergiodxa** [comment]
You can also leave the stuffs there, maybe not so much for client-side stuffs but server-only things can be 100% left untouched if not needed (or not needed now) and it shouldn't affect.

**Comment by swalker326** [comment]
I think the confetti represents my guiding principle. Its okay to have fun 😄

**Comment by kentcdodds** [comment]
I agree. But for some applications it's really just in the way. I do think it was a good call to remove this and make it an example instead. Challenging balance to strike here.
