### ISSUE TITLE
Why custom Prettier config?

### ISSUE THREAD

**Issue by ricardocosta** [epicweb-dev/epic-stack#537]
Previous requests around Prettier configuration changes (like #505 ) have been addressed with a general guideline of using Prettier's default configuration.

However, [`prettierrc.js`](https://github.com/epicweb-dev/epic-stack/blob/main/.prettierrc.js) seems to use a custom configuration, sometimes setting options to their default values (e.g. `printWidth`) and other times setting options to non-default values (e.g. `useTabs`).

I was wondering if this was a deliberate decision and what was the rationale behind it?

I tried to look for an entry in `docs/decisions` or in Discussions but I couldn't find anything concrete.

**Comment by kentcdodds** [comment]
I should probably write a decision doc about this, but really it's just my own preferences. I like the way the code looks as I have it configured. And in general I prefer to be explicit about the configuration (hence we configure even default values).

I don't know when I'll get around to writing a decision doc about this, but hopefully that's a good enough answer for now.

**Comment by ricardocosta** [comment]
Thanks for the feedback. 👍 

Even if you don't get to write a decision doc, having this issue and answer will already help other folks that have the same question.
