### ISSUE TITLE
deployment issues

### ISSUE THREAD

**Issue by felixyeboah** [epicweb-dev/epic-stack#546]
I have been trying to deploy a newly created project on fly but i always end up with this issue: 

WARN Failed to start remote builder heartbeat: failed building options: failed probing "personal": context deadline exceeded

Error: failed to fetch an image or build from source: error connecting to docker: failed building options: failed probing "personal": context deadline exceeded

any help?

**Comment by kentcdodds** [comment]
I'm sorry, I don't know what this could be. You'll probably need to reach out to fly support.
