### ISSUE TITLE
ENV is not defined

### ISSUE THREAD

**Issue by scefali** [epicweb-dev/epic-stack#555]
For some reason on my deployed app I am getting: 
```
entry.client.tsx:5 Uncaught (in promise) ReferenceError: ENV is not defined
    at entry.client.tsx:5:5
(anonymous) @ entry.client.tsx:5
```

Here is what that file looks like:
```
import { RemixBrowser } from '@remix-run/react'
import { startTransition } from 'react'
import { hydrateRoot } from 'react-dom/client'

if (ENV.MODE === 'development') {
	import('~/utils/devtools.tsx').then(({ init }) => init())
}
if (ENV.MODE === 'production' && ENV.SENTRY_DSN) {
	import('~/utils/monitoring.client.tsx').then(({ init }) => init())
}
startTransition(() => {
	hydrateRoot(document, <RemixBrowser />)
})
```

I guess `ENV` is a global variable? Does seem like magic this is supposed to work.

**Comment by scefali** [comment]
The weird part is the error seems to be intermittent as well.

**Comment by kentcdodds** [comment]
`ENV` gets set in two places:

1. On the server: https://github.com/epicweb-dev/epic-stack/blob/00c44b6bddf8da3b8c6594ffaede7a7b0c0765a4/app/entry.server.tsx#L19
2. On the client: https://github.com/epicweb-dev/epic-stack/blob/00c44b6bddf8da3b8c6594ffaede7a7b0c0765a4/app/root.tsx#L218

In both cases this is the earliest place we can set them from within the Remix app (won't work outside the Remix app).

I'm guessing for some reason you don't have the inline script for the client side of things.

**Comment by scefali** [comment]
@kentcdodds I have both those lines of code so something else must be up. I think I can just add protections if `ENV` is not defined.
