### ISSUE TITLE
AuthError while attempting github login

### ISSUE THREAD

**Issue by SangeetAgarwal** [epicweb-dev/epic-stack#556]
Right off the bat I get the following error while attempting to login using github. I just ran `npx create-epic-app@latest` and haven't made any modifications whatsoever.

> GET /login?_data=root 200 - - 14.408 ms
> GET /login?_data=routes/_auth+/login 200 - - 7.159 ms
> POST /auth/github?_data=routes/_auth+/auth.$provider 204 - - 12.301 ms
> GET /auth/github/callback?code=MOCK_CODE_GITHUB_KODY&state=a0u929rwrziqosiy6lddq0ch&_data=routes/_auth+/auth.$provider 204 - - 20.985 ms
> GET /auth/github/callback?code=MOCK_CODE_GITHUB_KODY&state=a0u929rwrziqosiy6lddq0ch&_data=root 200 - - 27.706 ms
> AuthorizationError: Not Found
>     at GitHubStrategy.failure (C:\git\frontend-learn\node_modules\remix-auth\build\strategy.js:37:23)
>     at GitHubStrategy.authenticate (C:\git\frontend-learn\node_modules\remix-auth-oauth2\build\index.js:142:35)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     ... 6 lines matching cause stack trace ...
>     at queryImpl (C:\git\frontend-learn\node_modules\@remix-run\router\router.ts:2999:20) {
>   cause: Error: Not Found
>       at GitHubStrategy.authenticate (C:\git\frontend-learn\node_modules\remix-auth-oauth2\build\index.js:142:84)
>       at processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at loader32 (file:///C:/git/frontend-learn/app/routes/_auth+/auth.$provider.callback.ts:33:21)
>       at C:\git\frontend-learn\node_modules\@sentry\src\utils\instrumentServer.ts:215:1
>       at Object.callRouteLoaderRR (C:\git\frontend-learn\node_modules\@remix-run\server-runtime\dist\data.js:52:16)
>       at callLoaderOrAction (C:\git\frontend-learn\node_modules\@remix-run\router\router.ts:3911:16)
>       at async Promise.all (index 0)
>       at loadRouteData (C:\git\frontend-learn\node_modules\@remix-run\router\router.ts:3220:19)
>       at queryImpl (C:\git\frontend-learn\node_modules\@remix-run\router\router.ts:2999:20)
>       at Object.queryRoute (C:\git\frontend-learn\node_modules\@remix-run\router\router.ts:2939:18)
> }
> GET /auth/github/callback?code=MOCK_CODE_GITHUB_KODY&state=a0u929rwrziqosiy6lddq0ch&_data=routes/_auth+/auth.$provider.callback 204 - - 143.782 ms
> GET /login?_data=root 200 - - 20.986 ms
> GET /login?_data=routes/_auth+/login 200 - - 11.425 ms

**Comment by Milind-Jamnekar** [comment]
have u run `npm run studio` as per the [documentation](https://github.com/epicweb-dev/epic-stack/blob/main/docs/getting-started.md#development)
