### ISSUE TITLE
Why eslint prettier plugin?

### ISSUE THREAD

**Issue by fdietze** [epicweb-dev/epic-stack#577]
Hey again! Just looked at my editor and wondered why the formatting check is a linter rule:

https://github.com/epicweb-dev/epic-stack/blob/2db44703aaaef5e59441015ee09845eed0a04fbe/.eslintrc.cjs#L10

![image](https://github.com/epicweb-dev/epic-stack/assets/1186516/7e7f916a-7e77-4176-add7-3dc2015bfabb)
# :see_no_evil: 

Looking at the [eslint docs](https://prettier.io/docs/en/integrating-with-linters.html#notes), it turns out that:
> These plugins were especially useful when Prettier was new. By running Prettier inside your linters, you didn’t have to set up any new infrastructure and you could re-use your editor integrations for the linters. But these days you can run prettier --check . and most editors have Prettier support.

So it probably makes sense to remove those. Or am I overlooking something again?

**Comment by ananni13** [comment]
That is **not** [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier), which just like you found in the prettier docs is not recommended anymore.

The project is using [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier), which practically does the opposite: it turns off all lint rules that might conflict with prettier.

I'm not sure why you're seeing all those errors in the editor, it might be some wrong vscode settings/extensions.
Did you change anything related to the lint configurations? Try to run `npm run lint` from your terminal to double check, it should pass without errors.

**Comment by kentcdodds** [comment]
Yep. Thanks @ananni13 👍

**Comment by fdietze** [comment]
Thank you for the explanation. Feels extremely weird to me that the linter has rules which conflict with formatting. But I guess that's just javascript land...
