### ISSUE TITLE
Flaky onboarding with link test

### ISSUE THREAD

**Issue by andrecasal** [epicweb-dev/epic-stack#579]
The `onboarding with link` test sometimes fails with a `403 Invalid CSRF token` error.

To replicate, run `npm test:e2e:dev` and run all tests multiple times.

You'll see the `onboarding with link` failing with an `403 Invalid CSRF token` error eventually.

**Comment by kentcdodds** [comment]
Hey @andrecasal!

I just tried this myself and I was unable to reproduce with a fresh bootstrap of a new Epic Stack app. I ran the tests 10 times to be sure. Sorry!
