### ISSUE TITLE
All traffic marked as direct in analytics (GA4 and Fathom)

### ISSUE THREAD

**Issue by bradymwilliams** [epicweb-dev/epic-stack#580]
Recently migrated to the Epic Stack from a custom stack hosted on Vercel

Using the default epic stack `server/index.ts` all traffic in analytics has switched from Organic Seo to Direct in multiple analytics providers so I think theres a problem I don't understand in the redirects middlewares?

**Comment by kentcdodds** [comment]
That's odd. The Epic Stack doesn't track analytics so I can't determine whether the Epic Stack actually has that same issue, but the Epic Stack is largely based on my personal website and [my analytics](https://kcd.im/kcd-fathom) definitely shows referrers. I'm afraid I don't know what could be causing your issues 😬

**Comment by bradymwilliams** [comment]
Fair enough. Curious are you pointing both www and @ sites to the same app in Fly? Wondering if a redirect there is at play.

**Comment by kentcdodds** [comment]
There's no automatic redirect (though I considered doing that).

**Comment by kentcdodds** [comment]
@bradymwilliams did you figure out what the problem was?

**Comment by bradymwilliams** [comment]
@kentcdodds Not when you messaged me, but I believe I just barely have. The client-hints script runs and on cookie changes runs `window.location.reload();` which refreshes and sets the referrer to the current page (which makes sense). Given its inline it hits before analytics does.
