### ISSUE TITLE
Admin protected routes are not showing relevant error message.

### ISSUE THREAD

**Issue by aerojeyenth** [epicweb-dev/epic-stack#583]
**Steps to reproduce:**

1. Login to epic stack with a non-admin user 
2. Navigate to ./admin/cache route
3. Observe the error message 

**Actual behavior:** 

Error message is undefined
`Cannot read properties of undefined (reading 'message')`

**Expected behavior:**

Relevant error message:

`Unauthorized: required role: admin`

Please find the screenshot attached. 

![image](https://github.com/epicweb-dev/epic-stack/assets/6432625/72712eec-d307-4af9-b393-3c4b473e86a0)

**Comment by kentcdodds** [comment]
Good catch. Would you be interested in submitting a PR to fix this?

**Comment by aerojeyenth** [comment]
> Good catch. Would you be interested in submitting a PR to fix this?

Sure. ! Do you want to give me any pointers ? My initial thought is fix is needed in the <GeneralErrorBoundary />

**Comment by kentcdodds** [comment]
I'd have to dig in a little bit. You should probably start in that route and trace the code.

**Comment by paolapog** [comment]
Hello @kentcdodds and @aerojeyenth,  I've found a way to solve this issue, I don't know if the most correct one but let me know, at least we have some clue :) 
cheers

**Comment by kentcdodds** [comment]
Thanks!
