### ISSUE TITLE
`extended-theme` defining Accordion-specific keyframes... but no accordion is used anywhere

### ISSUE THREAD

**Issue by simonswiss** [epicweb-dev/epic-stack#586]
The `extended-theme` is adding `keyframes` use for the [Accordion (Radix UI) component only](https://ui.shadcn.com/docs/components/accordion), and relying on Radix CSS variables — but no Accordion component is used anywhere in the app:

https://github.com/epicweb-dev/epic-stack/blob/3a9b80511361f40659b486e6721e0aeb7cadf2b2/app/utils/extended-theme.ts#L96-L99

This is a bit confusing, because those animation utilities will *not* work outside of Accordions (the CSS variables are missing), and... there are no Accordions used anywhere in the app.

Should these be removed, or is it here in case users want to start using Accordions?

**Comment by kentcdodds** [comment]
Yeah, that's a mistake. We can remove it.
