### ISSUE TITLE
Improve Mozilla Observatory score

### ISSUE THREAD

**Issue by MichaelDeBoey** [epicweb-dev/epic-stack#620]
The following link shows the score of https://kentcdodds.com: https://observatory.mozilla.org/analyze/kentcdodds.com

**Comment by kentcdodds** [comment]
I'm willing to accept PRs to improve things generally, but I warn anyone that these sorts of things should only be used to call attention to possible improvements and otherwise should be ignored. Machines are bad at grading good UX.

This definitely deserves a blog post eventually.
