### ISSUE TITLE
Upgrade Epic-Stack to use Remix 2.7.0 with Vite Stable Support

### ISSUE THREAD

**Issue by aerojeyenth** [epicweb-dev/epic-stack#623]
Remix Vite is Now Stable

Since Remix Vite is not Stable from version 2.7.0 

https://remix.run/blog/remix-vite-stable

Can we migrate Epicstack to use Vite ?

**Comment by kentcdodds** [comment]
Yes, I definitely would like to do this. I've tried it on my own site and the Epic Web workshop app and it's awesome. I'm open to anyone making a pull request if anyone's up for it. I'm pretty busy [preparing for this right now](https://www.epicweb.dev/events/epic-react-workshop-series-2024-03) 😅

**Comment by kentcdodds** [comment]
This is done 🎉
