### ISSUE TITLE
The branch ref check in deploy might not be needed

### ISSUE THREAD

**Issue by hilja** [epicweb-dev/epic-stack#628]
Correct me if I’m mistaken but this seems extra:

https://github.com/epicweb-dev/epic-stack/blob/534641c3920624263eb42056e2d258b343352b05/.github/workflows/deploy.yml#L143-L146

Since the push and the branches are already set:

https://github.com/epicweb-dev/epic-stack/blob/534641c3920624263eb42056e2d258b343352b05/.github/workflows/deploy.yml#L2-L6

**Comment by kentcdodds** [comment]
True. That could be simplified to just check for the event_name.

**Comment by misiewiczmichal** [comment]
Could I work on this? It would be my first PR.

**Comment by kentcdodds** [comment]
Sure!
