### ISSUE TITLE
e2e test expect the page to have changed url but doesn't wait for it to change

### ISSUE THREAD

**Issue by fredericrous** [epicweb-dev/epic-stack#645]
On my 2019 16" mac, the tests do not run fast enough.
I cannot expect the url to have changed after a test clicks a button.

For example, in `onboarding.test.ts` this code won't work:

https://github.com/epicweb-dev/epic-stack/blob/9741885c6fadc715ff502356164c6ec92782e1a2/tests/e2e/onboarding.test.ts#L46-L48

however this code does work:

```js
  await createAccountLink.click()

  await page.waitForURL('/signup');
```

we can just replace `toHaveURL` with `waitForURL`. I mean the test should fail if waitForURL does not resolve, therefore no need to `expect` on top of `waitForURL`, right?
Final word, I'm not saying to replace all `expect(page).toHaveURL` with `await page.waitForURL`. The ones after `await page.goto` are fine

also the timeouts are too short. I need to set globaly at least `timeout: 20 * 1000`. and for the onboarding test `reset password with a short code` I need to set it to `test.setTimeout(30 * 1000);`

**Comment by kentcdodds** [comment]
Interesting. I believe the assertion will wait just as long as the wait utility does. So maybe increasing the timeout is the right solution for you.

**Comment by fredericrous** [comment]
good catch @kentcdodds indeed the timeout for expect is different. I only modified the timeout for tests.

This also made me realise my tests are taking longer due to how I configured i18next instantiation. I'll be closing the issue and will add my findings to https://github.com/rperon/epic-stack-with-i18n/issues/8

thank you for the quick answer
