### ISSUE TITLE
Tailwind CSS is not updated

### ISSUE THREAD

**Issue by quangIle** [epicweb-dev/epic-stack#653]
Hello,

I am experienced with the issue where Tailwind CSS is not applied after changed.
My current workaround is to import the css file directly in dev mode:
```js
import fontStyleSheetUrl from './styles/fonts-stylesheet.css?url'
process.env.NODE_ENV === 'development' && import('./styles/tailwind.css')
```

I look forward to hearing from you.

**Comment by kentcdodds** [comment]
Odd. This seems like a vite bug. Could you try to reproduce this without the epic stack to help determine what the actual problem could be?

**Comment by kiliman** [comment]
I'm pretty sure it's a hydration issue. (It's always a hydration issue)

Use React Canary, and Tailwind+HMR should work correctly.

**Comment by quangIle** [comment]
I tried to reproduce this without epic stack. Also, I tried it with and without React Canary and it still occurred. Here is the link to the reproduce code: https://stackblitz.com/edit/remix-run-remix-3nnng7?file=app%2Froot.tsx

But I think that this line in `links` is the reason because when I removed it, the code worked properly

```ts
export const links: LinksFunction = () => [
  ...
  // Preload CSS as a resource to avoid render blocking
  { rel: 'preload', href: tailwindStyleSheetUrl, as: 'style' },
  ...
];
```

**Comment by kentcdodds** [comment]
We're probably safe to remove that since the stylesheet shows up in the HTML pretty immediately anyway. I don't think having a preload a couple lines above it in the HTML is going to make a difference.
