### ISSUE TITLE
Incompatible @typescript-eslint/typescript-estree dependency

### ISSUE THREAD

**Issue by kgoggin** [epicweb-dev/epic-stack#655]
Hello! I just created a new project via `npx create-epic-app@latest`. I'm running into an error when running eslint locally:

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0

YOUR TYPESCRIPT VERSION: 5.3.3

Please only submit bug reports when using the officially supported version.

=============
```

From what I can tell, the linting just... isn't running. This also means lint errors don't show up in my editor (VS Code).

The lint task _does_ work when run via Github Actions (which is how I figured this out -- I pushed up a commit with an error and the check failed). I thought maybe `npm ci` was installing things slightly differently, but I tried that locally and still get the same error. I'm not sure what to make of that? I'm running node v20.9.0 locally, not sure if that'd affect things.

I also tried directly installing the latest version of `@typescript-eslint/typescript-estree` (which is 7.2.0), but I think the sub-dependency of @remix-run/eslint-config@"^2.8.1" is still winning out?

I re-installed another epic web project just to double-check it wasn't something else I'd done in my main project and see the same thing. So, there's a chance it's just something with my local environment, I suppose? Not sure what that could be besides node version though 🤔.

**Comment by kentcdodds** [comment]
I know that the Remix team is going to be deprecating their linting config and my personal linting config is pretty dated and a little over-zealous.

I'm planning on putting together and epic eslint config in the future and that should resolve this problem. Hopefully I can get that done in the next couple months.

**Comment by kentcdodds** [comment]
Oh, and to be clear, the linting is in fact running properly for me. I'm not so certain what the issue is in your setup. Sorry!

<img width="1677" alt="screenshot of vscode showing a failing eslint rule in the editor and terminal" src="https://github.com/epicweb-dev/epic-stack/assets/1500684/a67ecafe-aa72-4683-b106-1ff271e0a3aa">
