### ISSUE TITLE
[documentation] missing for github auth

### ISSUE THREAD

**Issue by fredericrous** [epicweb-dev/epic-stack#657]
It'd be nice to get doc on github auth setup in https://github.com/epicweb-dev/epic-stack/blob/main/docs/deployment.md

I'm thinking of a link to github oauth settings page, the instructions to enter like the url and the callback

a link to the token and the authorization to select

**Comment by kentcdodds** [comment]
Good idea! We do cover it here: https://auth.epicweb.dev/17

But having some docs specifically about setting up the GitHub side would be good

**Comment by fredericrous** [comment]
is `read:user` the correct authorizations for the token expected by GITHUB_TOKEN?

**Comment by kentcdodds** [comment]
I just follow the instructions here: https://github.com/sergiodxa/remix-auth-github

**Comment by kentcdodds** [comment]
Thanks @rustworthy!
