### ISSUE TITLE
Create an account button shows error but should not

### ISSUE THREAD

**Issue by fredericrous** [epicweb-dev/epic-stack#671]
**Reproduction workflow**

1. setup the project without database seed:
    - clone the project
    - cd to the cloned folder
    - cp .env.example .env
    - npm install
    - setup without seed: npx prisma generate && npx prisma migrate deploy
    - npm run dev

3. then, connect with github:
    - click the login with github button
    - get automatically redirected to `/onboarding/github?redirectTo=%2Flogin`
    - notice the status on the button tells the user there is an error but there is none

<img width="1095" alt="image" src="https://github.com/epicweb-dev/epic-stack/assets/702227/c1f622f3-752f-4182-a858-8ad74b3c1a2f">

**Comment by kiliman** [comment]
Seed data is required for the Epic Stack to function correctly. It creates the roles and permissions needed for account creation.

I'm unsure why you would not want to run the setup process.

**Comment by kentcdodds** [comment]
The seed data is no longer required for the Epic Stack to function. We seed roles and permissions in the migrations.

Help is wanted to investigate what's going on here.

**Comment by kentcdodds** [comment]
Thanks @rustworthy!!
