### ISSUE TITLE
Vitest fails after Prisma migration

### ISSUE THREAD

**Issue by andrecasal** [epicweb-dev/epic-stack#674]
I migrated the DB to a simpler format.

Naturally, this got the testing database at `./tests/prisma/base.db` out of sync with the Prisma client and most Vitest tests fail.

It would be nice if, everytime we run a migration, we also delete the test database so that Vitest setup re-runs the setup and copies `./prisma/data.db` over to `./tests/prisma/base.db`.

**Comment by kentcdodds** [comment]
Running migrations just takes a while so we cache it. We could add logic that checks the modified time of the schema to determine whether the database should be updated. Shouldn't be super complicated. PRs welcome!
