### ISSUE TITLE
Fly volume in wrong region

### ISSUE THREAD

**Issue by joshmedeski** [epicweb-dev/epic-stack#68]
I've been following the README and when I deployed I got this error.

> Error: error creating a new machine: failed to launch VM: Mounts source volume "vol_lgz1vppx35yv78m3" is in the wrong region ("dfw" != "iad")

So, I created a new volume in `iad` and I got this message:

> Error: error creating a new machine: failed to launch VM: Mounts source volume "vol_1q85vg7xkgzvzdxe" is in the wrong region ("iad" != "dfw")

What's happening? When I created the apps I wasn't asked for a region and when I created the volumes I chose `dfw` for both.

**Comment by joshmedeski** [comment]
I just deleted my apps and volumes and tried again with a new name and I got this:

> Error: error creating a new machine: failed to launch VM: Mounts source volume "vol_915grnw3g9krn70q" is in the wrong region ("dfw" != "sjc")

Not sure what's going on. I'd love to get the Epic Stack up and running before committing to the stack to develop my next product.

**Comment by kentcdodds** [comment]
Hi @joshmedeski,

I'm afraid there's not much I can do to help you in this. I would suggest you go to https://community.fly.io to see what's up with your app. They're pretty responsive.

**Comment by chessydk** [comment]
I had the same problem and found out that you need to specify your primary region in the fly.toml file. https://fly.io/docs/reference/configuration/#primary-region

The error comes because connected volumes and machines have to be in the same region!
