### ISSUE TITLE
Rate limiting can be bypassed with a spoofed ip

### ISSUE THREAD

**Issue by nickjamesio** [epicweb-dev/epic-stack#682]
First off, thanks for creating the epic stack! I'm learning about rate limiting so I thought I'd use epic-stack for reference. While looking over the repo, these two lines caught my attention: 

- https://github.com/epicweb-dev/epic-stack/blob/800022dae82530dd48ef0ba35abe666eac1c619e/server/index.ts#L152
- https://github.com/epicweb-dev/epic-stack/blob/800022dae82530dd48ef0ba35abe666eac1c619e/server/index.ts#L39

I was curious to see if it is indeed impossible to spoof `X-Forwarded-For`. I came across this forum post https://community.fly.io/t/recommended-setting-for-trust-proxy-on-express/6346 and I tried the curl request they provided and it looks like you can indeed spoof `X-Forwarded-For`.

Request for spoofing IP
`curl -sv\
    -H "Host: injected.host"\
    -H "X-Forwarded-Proto: injected"\
    -H "X-Forwarded-For: 1.2.3.4"\
    -H "X-Forwarded-Port: 1234"\
    -H "X-Forwarded-Ssl: maybe"\
    https://debug.fly.dev/`

While looking at express-rate-limit, it looks like it uses `req.ip` as the unique identifier. See [here](https://github.com/express-rate-limit/express-rate-limit/blob/fe37463bb24269e1963c340da72f123158f4d4b6/source/lib.ts#L220)

The express docs have this to say about req.ip

> The [req.ip](https://expressjs.com/en/api.html#req.ip) and [req.ips](https://expressjs.com/en/api.html#req.ips) values are populated based on the socket address and X-Forwarded-For header, starting at the first untrusted address.

I ran the epic stack locally and I could indeed get past the rate limiting with a spoofed IP. See [this loom video](https://www.loom.com/share/8c61315930d74f4dbaa37423cee9f284)

Based on this info, I am pretty sure rate limiting can be bypassed when an epic stack application is hosted in fly.io I think one solution would be to use the `Fly-Client-Ip` header since it would appear that header cannot be spoofed.

**Comment by kentcdodds** [comment]
Nice find! I welcome a PR to switch our implementation to use the `Fly-Client-Ip` header!

**Comment by nickjamesio** [comment]
I will def work on it!

**Comment by andrecasal** [comment]
Great work Nick!

**Comment by nickjamesio** [comment]
Been a busy week but I did get a chance to do some testing. It looks like Fly-Client-Ip can indeed work. One edge case though. If someone has a proxy in front of the app like Cloudflare, Fly-Client-Ip will contain the IP of Cloudflare, not the end user.

I did a quick search and it does not look like epic-stack requires the use of cloudflare. However, it can have unintended consequences if someone uses Cloudflare and is unaware. Do you have a recommendation on where to mention this or if it should be mentioned at all?

**Comment by kentcdodds** [comment]
Hmmmm... It definitely should be mentioned. Can probably just do a code comment. People making changes is always going to affect the assumptions we make and we can't over-complicate the codebase for every possible change people make to the stack.

**Comment by kentcdodds** [comment]
Hi @nickjamesio, are you still planning on working on this?

**Comment by nickjamesio** [comment]
Hey! Sorry about that and thanks for the nudge. I will be back from traveling in one week. I will take a look when I get back if no one has fixed it by then. Marking my calendar :)

**Comment by nickjamesio** [comment]
Just want to say I have some time this evening to work on this :)

**Comment by nickjamesio** [comment]
Thanks! My plan is to add a code comment around CDNs but use Cloudflare as an example. I won't be adding any special logic for CF though.

Spoofing CF-Connecting-IP is something I have also thought of so thanks for the mention. I think I found a solution, however, it is Cloudflare specific.  [Authenticated origin pull](https://community.cloudflare.com/t/how-to-make-my-backend-only-accept-requests-from-cloudflare/216586/3)

**Comment by andrecasal** [comment]
Hey @nickjamesio  👋 I'd like to write a test for this. Could you provide the request you've used to test it?

@kentcdodds would you want to add security tests to the Epic Stack?

**Comment by kentcdodds** [comment]
That sounds great depending on how complicated it is and how reliable they are. An example is always welcome!

**Comment by nickjamesio** [comment]
@andrecasal I did my testing in the browser but I can explain my process. I lowered the rate limit for the strongest endpoints down to 2 and tried logging in using invalid credentials. Attempt to login a few times and it will trigger the rate limit.

**Comment by kentcdodds** [comment]
I think this is kind of testing a dependency so I'm not sure I want to include it. Thanks though!

**Comment by andrecasal** [comment]
Good point. Would it be worth testing the IP spoofing?

**Comment by kentcdodds** [comment]
Perhaps! Definitely interested in seeing what a playwright test like that would look like.
