### ISSUE TITLE
dev-server long running command does not give back shell input correctly on fish shell

### ISSUE THREAD

**Issue by fredericrous** [epicweb-dev/epic-stack#688]
I'm using `fish` shell on mac, and whenever I close the dev server, the input of the shell is messed up, I cannot see what I am writing, the up command shows `^[[A` instead of going back one line in history

basically I'm seeing this

<img width="635" alt="image" src="https://github.com/epicweb-dev/epic-stack/assets/702227/3093a6dc-207b-4e82-b8fa-5738b77fdd1a">

the issue goes away when I execute a new command. it can also be a fake command. I generally do `ls`

note: I'm using hyper terminal but I can reproduce this inside VSCode. I do not seem to get the issue with zsh

I think the issue comes from https://github.com/epicweb-dev/epic-stack/blob/d663177944e97f2705ec69482d3cc3c56865b2c8/server/dev-server.js#L9
input is ignored.. and stays ignored even after a Ctrl+C, until I execute a new command

**Comment by kentcdodds** [comment]
I'm not certain this is an issue with the epic stack. Feels like an issue for execa or something wrong with your system. So I'm going to close this issue. Sorry!

**Comment by fredericrous** [comment]
I'm sure all it takes to reproduce the issue is to install fish and try it for yourself. On my end no worries, I fixed the issue. I just wanted to share the solution

**Comment by kentcdodds** [comment]
Thanks!
