### ISSUE TITLE
dependency check

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/epic-stack#69]
running `npx depcheck ` reveals some unused and missing dependencies

**Unused dependencies**
* @radix-ui/react-popover
* @radix-ui/react-separator
* @radix-ui/react-tabs
* @reach/dialog
* downshift
* remix-auth-socials
* spin-delay

**Missing dependencies**
* esbuild: .\other\build-server.ts

there are also report for **Unused devDependencies** but i don't sure how to check if those are really unused
<details>
  <summary>Unused devDependencies</summary>

* @remix-run/testing
* @testing-library/dom
* @testing-library/jest-dom
* @testing-library/react
* @testing-library/user-event
* @types/eslint
* @types/testing-library__jest-dom
* @types/uuid
* @vitest/coverage-c8
* autoprefixer
* c8
* postcss
* prettier-plugin-sql
* prettier-plugin-tailwindcss
* tailwindcss
* tailwindcss-radix
* tsconfig-paths
* vitest-mock-extende

</details>

**Outdated dependencies**
 @faker-js/faker                ^7.6.0  →   ^8.0.1 🔴
 @remix-run/router              ^1.6.1  →   ^1.6.2
 @testing-library/dom           ^9.2.0  →   ^9.3.0
 @types/cookie                  ^0.5.0  →   ^0.5.1
 @types/glob                     7.2.0  →    8.1.0
 @types/node                  ^18.16.3  →  ^20.2.1
 @vitest/coverage-c8           ^0.31.0  →  ^0.31.1
 chalk                          ^4.1.2  →   ^5.2.0 🔴
 glob                           ^7.2.3  →  ^10.2.5 🔴
 lru-cache                     ^7.18.3  →   ^9.1.1 🔴
 prettier-plugin-tailwindcss    ^0.2.8  →   ^0.3.0
 vite                           ^4.3.5  →   ^4.3.8
 vitest                        ^0.31.0  →  ^0.31.1

we can upgrade to chalk 5.2.0 now that we are using ESM
why you are still using year old glob?

**Comment by onemen** [comment]
there are some breaking changes

**@faker-js/faker ^7.6.0 → ^8.0.1**
[upgrading faker to v8](https://fakerjs.dev/guide/upgrading.html)
faker deprecate [`helpers.unique` #1785](https://github.com/faker-js/faker/issues/1785) for removal in version 9.0, we need to find a replacement or write the code

**chalk ^4.1.2 → ^5.2.0**
chalk 5.2.0 **does not work** for me on development mode `npm run dev`, the script just hang after `Mock server installed`.
using `npm run build`  and `npm start` **work ok**.

@kentcdodds , can you check `lru-cache`?

**Comment by onemen** [comment]
Done in #116

**Comment by MansurAliKoroglu** [comment]
@onemen 

I created an npm package to be used as a replacement to unique.

https://github.com/MansurAliKoroglu/enforce-unique

https://www.npmjs.com/package/enforce-unique

**Comment by kentcdodds** [comment]
Thanks! I'd definitely accept a pull request to use that module.
