### ISSUE TITLE
No relative import paths

### ISSUE THREAD

**Issue by zwhitchcox** [epicweb-dev/epic-stack#698]
Relative imports make refactors harder as well as searching for imports

This eslint rule:

```ts
		{
			'no-relative-import-paths/no-relative-import-paths': [
				'warn',
				{ allowSameFolder: false, rootDir: '.', prefix: '#' },
			],
		},
```

can ensure there are no relative imports.

Wanted to check before I made a PR.

**Comment by kentcdodds** [comment]
Did you change your mind?

**Comment by zwhitchcox** [comment]
I added this to #696,  cause they are closely related, but can separate the two if preferred.
