### ISSUE TITLE
/swapon command failing when deploying to production

### ISSUE THREAD

**Issue by lewisblackburn** [epicweb-dev/epic-stack#701]
The way swap files are created has recently changed on fly.io. I don't think the setup-swap.js file is needed anymore and we can just add `swap_size_mb` in `fly.toml`.

Here is the blog post by fly: https://community.fly.io/t/a-new-way-to-rootfs/19196.

**Comment by kentcdodds** [comment]
Nice find! I welcome a pull request!

**Comment by kinggoesgaming** [comment]
I can get it in a few hours (currently at work)
