### ISSUE TITLE
Running Vitest locally can cause errors due to missing schema updates in test database

### ISSUE THREAD

**Issue by DennisKraaijeveld** [epicweb-dev/epic-stack#711]
Like mentioned in Discord, I ran into a problem where my new tests failed, ran locally, due to missing database tables and columns. The reason why this happened is because the `base.db` already existed within `test/prisma`. Looking at the global-setup.ts we find the following:

```ts
const databaseExists = await fsExtra.pathExists(BASE_DATABASE_PATH)

if (databaseExists) return

# some Prisma migrate script if database is not there yet
```

To enable Prisma schema updates without manually removing the base.db I propose we do something like this to make sure the base.db only will be generated/seeded when there has been a update within the Prisma schema

```ts

export async function setup() {
	// Check if the database exists
	const databaseExists = await fsExtra.pathExists(BASE_DATABASE_PATH)

	if (databaseExists) {
		const databaseLastModifiedAt = (await fsExtra.stat(BASE_DATABASE_PATH))
			.mtime
		const prismaSchemaLastModifiedAt = (
			await fsExtra.stat('./prisma/schema.prisma')
		).mtime

		if (prismaSchemaLastModifiedAt < databaseLastModifiedAt) {
			return
		}
	}

	await execaCommand('npx prisma migrate reset --force --skip-generate', {
		stdio: 'inherit',
		env: {
			...process.env,
			MINIMAL_SEED: 'true',
			DATABASE_URL: `file:${BASE_DATABASE_PATH}`,
		},
	})
}
```

Like this it will apply schema changes without the need of manually removing the db yourself.

**Comment by kentcdodds** [comment]
PR welcome!

**Comment by DennisKraaijeveld** [comment]
> PR welcome!

Done 👍

**Comment by kentcdodds** [comment]
Thanks!
