### ISSUE TITLE
Incomplete Setup Using npx create-remix@latest

### ISSUE THREAD

**Issue by nikitakent** [epicweb-dev/epic-stack#758]
**Description**
While following the [Getting Started ](https://github.com/epicweb-dev/epic-stack/blob/main/docs/getting-started.md)guide, I ran npx create-remix@latest to create a new Remix application. However, I noticed that several steps, including the Prisma setup, were missing.

**Steps to Reproduce**
Follow the Getting Started guide using MacBook Pro with M1 chip. 
Run the command: npx create-remix@latest.

**Expected Behavior**
The setup should include all necessary configurations, including Prisma setup and other essential steps, to get the application running easily.

**Actual Behavior**
The setup was incomplete and did not include Prisma setup, among other necessary configurations.

**Workaround**
I tried the following command and was able to get the complete (expected) boilerplate set up:

`SKIP_SETUP=false SKIP_FORMAT=false SKIP_DEPLOYMENT=false npx create-epic-app@latest`

This command ensured that all required setup steps were executed correctly.

Could you please update the Getting Started guide and the npx create-remix@latest command to ensure that all necessary setup steps are included by default?

Thank you!

**Comment by kentcdodds** [comment]
What @kiliman said 👆 

Let us know if there's anything else :)
