### ISSUE TITLE
Remove `installGlobals` calls

### ISSUE THREAD

**Issue by kinggoesgaming** [epicweb-dev/epic-stack#802]
The globals added by `installGlobals` are now natively available with `node` 20+

Ref: https://github.com/remix-run/remix/issues/7067#issuecomment-2225843886

**Comment by kinggoesgaming** [comment]
Ok I think I might have misunderstood that comment. Need a second opinion before I anything here

**Comment by kinggoesgaming** [comment]
> Ok I think I might have misunderstood that comment. Need a second opinion before I anything here

Looking further.. I am correct on the fact that `installGlobals` is no longer needed

**Comment by kentcdodds** [comment]
Yeah, we can remove that I think
