### ISSUE TITLE
Project is missing /public/fonts folder

### ISSUE THREAD

**Issue by MoSattler** [epicweb-dev/epic-stack#815]
I am currently playing around with [catalyst](https://catalyst.tailwindui.com), and [one of their recommendations is using the inter font](https://catalyst.tailwindui.com/docs#optional-setup-inter-font-family). 

I checked out the [documentation for adding custom fonts](https://github.com/epicweb-dev/epic-stack/blob/main/docs/fonts.md#using-custom-fonts), and it mentions I need to add something to `/public/fonts`. But this folder does not seem to exist in freshly created epic stacks.

**Comment by kentcdodds** [comment]
Yeah, you create that folder. A PR is welcome to make it more clear if you'd like :)
