### ISSUE TITLE
POST requests turn into GET

### ISSUE THREAD

**Issue by CodingAleCR** [epicweb-dev/epic-stack#818]
Hey all, I'm working on a chatbot (with Botpress Cloud) that accesses my information via API routes. The problem is that the service I'm using, goes through a proxy. When it gets to my express server, the server receives the request as an HTTP request instead of an HTTPS and the middleware set by default on the express server performs the redirect to HTTPS but loses the request method.

So TLDR; 

POST request -> Express Middleware -> GET request

```javascript
app.use((req, res, next) => {
	const proto = req.get('X-Forwarded-Proto')
	const host = getHost(req)
	if (proto === 'http') {
		res.set('X-Forwarded-Proto', 'https')
		res.redirect(`https://${host}${req.originalUrl}`)
		return
	}
	next()
})
```

I've tried doing a couple of things I've found around by adding codes `308` and `307` but then the request gets lost and the chatbot ends with network errors (error shown: `AxiosError: Network Error`). 

```javascript
if (req.method === 'POST') {
	res.redirect(307, `https://${host}${req.originalUrl}`)
	return
}
```

I'm not sure if this is the right place to ask for suggestions so I'd appreciate guidance on how to make things work with this.

**Comment by kentcdodds** [comment]
I'd suggest adding this to the top of that middleware:

```ts
if (req.method !== 'GET') return next()
```

I'd happily merge a PR for this 😁

**Comment by CodingAleCR** [comment]
Thank you, that worked, just out of curiosity. This will make it so that POST (or others) request don't get redirectected to HTTPS right? What are the implications of this on the project (just for awareness)

**Comment by kentcdodds** [comment]
It's highly unlikely there will be any practical negative implications from this change. Would you like to make a pull request to make this change in the stack?
