### ISSUE TITLE
Add .cursorrules

### ISSUE THREAD

**Issue by mohammedzamakhan** [epicweb-dev/epic-stack#836]
Add .cursorrules file to the repo and also submit it to https://cursor.directory/

**Comment by kentcdodds** [comment]
Hi @mohammedzamakhan! It's been a while! Nice to see you again.

I'm not sure I want to put this in the epic stack as a default. I really don't like having files in the root of a project. It just gets very busy. If it could go in the `.vscode` directory which we already have then I would be fine with that though.

**Comment by mohammedzamakhan** [comment]
Thanks @kentcdodds :) That makes sense to me.
