### ISSUE TITLE
Found a very strange error(It seems to reload once (twice total)

### ISSUE THREAD

**Issue by Alvazz** [epicweb-dev/epic-stack#839]
I followed the standard documentation line by line without adding any additional steps, then ran it, opened the browser to access it, and found that when loading the page, it seemed to reload once (twice in total) and then I saw this error log through the browser console.

<img width="1661" alt="image" src="https://github.com/user-attachments/assets/3301aaa0-bb96-4c29-8da0-95bd9c4a1ac1">

**Comment by lsbyerley** [comment]
It's the hydration mismatch error. It appears to be coming from the nonce value in the links scripts. I've tried to fix this but to no avail. This article will give you some context on the issue https://www.jacobparis.com/content/remix-hydration-errors

**Comment by kentcdodds** [comment]
I've just added a documentation bit about this: https://github.com/epicweb-dev/epic-stack/blob/main/docs/troubleshooting.md#hydration-mismatch

**Comment by hilja** [comment]
> The browser strips the nonce from the DOM before executing any JavaScript for security reasons

Great to know! I almost lost my mind debugging this :)
