### ISSUE TITLE
Missed update from #837

### ISSUE THREAD

**Issue by natac13** [epicweb-dev/epic-stack#844]
https://github.com/epicweb-dev/epic-stack/blob/c2e8ed608b27f376b99df97021988c496da2c816/app/routes/_seo%2B/sitemap%5B.%5Dxml.ts#L6

With the update from #837 I believe that the SEO sitemap configuration also needs an update to ensure it grabs the 'ServerBuild` from the return object

**Comment by kentcdodds** [comment]
Could you open a pull request for this? Thanks!

**Comment by natac13** [comment]
You bet! I'll have it to you by 1 est just have to wrap something up quick
