### ISSUE TITLE
Change Input component text size

### ISSUE THREAD

**Issue by braginteractive** [epicweb-dev/epic-stack#849]
Any reason why the Input component uses `text-sm`? 

This makes mobile devices zoom into the input because the font size is < 16px.  In most cases this makes the site have scrollbars once the user is done interacting with the input. 

Changing the class to `text-base` stops this zoom in behavior.

**Comment by kentcdodds** [comment]
I'm not sure I understand what you're talking about with the zoom

**Comment by braginteractive** [comment]
Here is an article on CSS Tricks and a video that shows the form zoom.

https://css-tricks.com/16px-or-larger-text-prevents-ios-form-zoom/

**Comment by kentcdodds** [comment]
Gotcha! Yeah, let's fix that. Care to open a pull request?

**Comment by kentcdodds** [comment]
Thank you!
