### ISSUE TITLE
formatting WRT to arrowParens is inconsistent

### ISSUE THREAD

**Issue by dalelotts** [epicweb-dev/epic-stack#865]
Existing code formatting for arrowParens is inconsistent - prettier is set to avoid but lots of code has the parens where they would not normally exist if formatted with prettier set to arrowParens='avoid'

**Comment by dalelotts** [comment]
I created a brand new project, committed the changes, ran `npm run format -- --arrow-parens avoid`, and the following files were changed

	modified:   app/components/error-boundary.tsx
	modified:   app/components/forms.tsx
	modified:   app/components/search-bar.tsx
	modified:   app/root.tsx
	modified:   app/routes/_auth+/auth.$provider.callback.test.ts
	modified:   app/routes/_auth+/auth.$provider.callback.ts
	modified:   app/routes/_auth+/login.tsx
	modified:   app/routes/_auth+/onboarding.tsx
	modified:   app/routes/_auth+/onboarding_.$provider.tsx
	modified:   app/routes/_auth+/signup.tsx
	modified:   app/routes/admin+/cache.tsx
	modified:   app/routes/resources+/download-user-data.tsx
	modified:   app/routes/resources+/healthcheck.tsx
	modified:   app/routes/resources+/theme-switch.tsx
	modified:   app/routes/settings+/profile.connections.tsx
	modified:   app/routes/settings+/profile.photo.tsx
	modified:   app/routes/settings+/profile.tsx
	modified:   app/routes/users+/$username.test.tsx
	modified:   app/routes/users+/$username_+/__note-editor.server.tsx
	modified:   app/routes/users+/$username_+/__note-editor.tsx
	modified:   app/routes/users+/$username_+/notes.$noteId.tsx
	modified:   app/routes/users+/$username_+/notes.index.tsx
	modified:   app/routes/users+/$username_+/notes.tsx
	modified:   app/routes/users+/index.tsx
	modified:   app/utils/cache.server.ts
	modified:   app/utils/db.server.ts
	modified:   app/utils/misc.tsx
	modified:   app/utils/misc.use-double-check.test.tsx
	modified:   app/utils/timing.server.ts
	modified:   app/utils/user-validation.ts
	modified:   app/utils/user.ts
	modified:   other/build-icons.ts
	modified:   prisma/seed.ts
	modified:   server/index.ts
	modified:   tests/db-utils.ts
	modified:   tests/mocks/github.ts
	modified:   tests/playwright-utils.ts
	modified:   tests/setup/custom-matchers.ts
	modified:   vite.config.ts

**Comment by kentcdodds** [comment]
> prettier is set to avoid

Where is prettier set to avoid?

**Comment by dalelotts** [comment]
Ah, my mistake. I see that .prettierrc* has been deleted since I created my project - not sure why it wasn't deleted when I pulled in the latest changes.

I used to be set to avoid in https://github.com/epicweb-dev/epic-stack/blob/5cb51100ddc97cd31ec53036c42f7fae7ff15572/.prettierrc.js#L3

**Comment by kentcdodds** [comment]
Ah, that makes sense! Here's why this was changed: https://github.com/epicweb-dev/config/blob/main/docs/decisions/006-arrow-parens.md

**Comment by dalelotts** [comment]
That ADR refers to a config change, but I don't see a .prettierrc* file in the project at the moment. 
I also do not see a decision to remove the prettier config entirely (but there is one about changing semi) 

Am I missing something?

**Comment by dalelotts** [comment]
Oh, that is a different project. I see what happened.
