### ISSUE TITLE
LiteFS Cloud will be retired

### ISSUE THREAD

**Issue by taylrd** [epicweb-dev/epic-stack#871]
LiteFS Cloud will be retired on Oct. 15, 2024. This may not be an issue for most but just wondering if there will be an update for the epic-stack? I would love to contribute to this but am unable to do so at this time. I'm sure that Kent is aware of this but just wanting to make sure.

**Comment by kentcdodds** [comment]
Hello @taylrd,

Yes, we're evaluating solutions here: https://github.com/epicweb-dev/epic-stack/discussions/858

Cheers!
