### ISSUE TITLE
epic-stack by default doesn't seem to report unhandled rejections to Sentry.

### ISSUE THREAD

**Issue by tmcw** [epicweb-dev/epic-stack#872]
We've been running into some issues with Sentry reporting in our epic-stack based application, and I think the issue is present in the base template - epic-stack calls `closeWithGrace` in its entrypoint:

https://github.com/epicweb-dev/epic-stack/blob/b19ac20b756707831cab51dd6a096a655f5d76a7/index.js#L21-L27

Which will register a `process.on('unhandledRejection'` error and exit before any other unhandledRejection listeners have time to respond, including Sentry's unhandledRejectionIntegration. The result is that unhandled rejections that cause the server to crash also are not reported to Sentry, because `closeWithGrace` calls `process.exit(1)` as soon as they are received by the first registered handler.

**Comment by kentcdodds** [comment]
Makes sense! What do you think would be the proper solution to this?

**Comment by tmcw** [comment]
The solution that I've proposed for our repo is that we remove `close-with-grace` from `index.js` because it's present in `remix-server/index.ts` anyway, and the closeWithGrace call there is updated to look like:

```ts
closeWithGrace(async ({ err }) => {
  Sentry.captureException(err);
  console.error(err);
  console.error("Shutting down, flushing Sentry events");
  await Sentry.flush(100);
  await new Promise((resolve, reject) => {
    server.close((e) => (e ? reject(e) : resolve("ok")));
  });
});
```

So manually capturing the exception with sentry there, as well as waiting for Sentry to flush events. That's the general shape of the solution - another way it could be solved would be to supply a `{delay:500}` option to the closeWithGrace call to let other handlers do their thing, but that seems like it'd be possibly introducing some uncertainty about whether Sentry is able to flush its events within that timespan.

**Comment by kentcdodds** [comment]
That seams like a reasonable solution. I'd welcome a PR for that. Thank you!

**Comment by tmcw** [comment]
Sure! Filed at #873
