### ISSUE TITLE
Disable "global" in vitest

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/epic-stack#9]
I tried and ran into TS issues. Would love to ditch it though.

**Comment by onemen** [comment]
@kentcdodds 

Can you provide the draft you are working on?

I will try to work on in

**Comment by kentcdodds** [comment]
I didn't save it. There wasn't much to it. Just remove some stuff from the vitest config and the tsconfig and things stopped working 😅 I didn't spend much time on it I'm afraid.

**Comment by onemen** [comment]
do you want to remove:

`globals` from `vitest.config.ts`:
```diff
  plugins: [react(), tsconfigPaths()],
  test: {
    include: ['./app/**/*.test.{ts,tsx}'],
-    globals: true,
    environment: 'jsdom',
    setupFiles: ['./other/test-setup/setup-test-env.ts'],
    globalSetup: ['./other/test-setup/global-setup.ts'],
```

or 
`global` from `setup-test-env.ts`

```
declare global {
  namespace Vi {
    interface JestAssertion<T = any>
      extends jest.Matchers<void, T>,
        TestingLibraryMatchers<T, void> {}
  }
}
```

or ...
